bolt-foundry/bfmono

AGENT.md, packages/bfDb/classes/BfEdgeInMemory.ts, packages/bfDb/classes/__tests__/BfEdgeBaseTest.ts, packages/bfDb/coreModels/BfEdge.ts
- Added step 7 to the BFF commit protocol documentation to delete GitHub user information file after use
- This ensures user privacy by removing sensitive data after the commit process
- Verified the documentation addition accurately describes the required cleanup step
- Confirmed the formatting matches existing documentation style
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/306).
* __->__ #306
* #305
* #303
* #302
* #301
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/306)
=> Add GitHub user information privacy cleanup step to AGENT.md

AGENT.md
- Renamed all occurrences of "BFF" to "BFA" in the Special Protocols section
- Updated protocol command examples to use "!bfa" instead of "!bff"
- Updated protocol section names to maintain consistency throughout documentation
- Verified all command references now use "!bfa" consistently
- Manual inspection of AGENT.md confirms all protocol references have been updated
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/307)
=> Update project references from BFF to BFA in AGENT.md

infra/bff/friends/ci.bff.ts, infra/bff/friends/githubAnnotations.ts, packages/bfDb/classes/BfEdgeBase.ts, packages/bfDb/classes/BfEdgeInMemory.ts, packages/bfDb/classes/__tests__/BfEdgeBaseTest.ts, packages/bfDb/coreModels/BfEdge.ts
- Added cache parameter to queryTargetInstances and queryTargetEdgesForNode methods in BfEdgeBase
- Implemented cache usage in BfEdgeInMemory for more efficient node lookups
- Added cache population logic in queryTargetEdgesForNode in BfEdgeInMemory
- Updated BfEdge to pass cache parameter to the underlying query method
- Added test cases to verify cache is properly used and populated
- Added specific test case "cache is used for queryTarget methods" that verifies cache population
- Tested cache usage with both queryTargetInstances and queryTargetEdgesForNode methods
- Verified that target nodes and edges are properly added to the cache map
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with …
=> Implement cache support for queryTarget methods in edge classes

AGENT.md, packages/bfDb/classes/BfCurrentViewer.ts
- Add documentation about using proper test inheritance patterns between base and derived classes
- Add comprehensive documentation for mocking CurrentViewer instances in tests
- Document the __DANGEROUS__createTestCurrentViewer helper method
- Emphasize using bff t instead of raw deno test commands
- Fix CI output file reference in the commit protocol section
- Verified formatting and content consistency in AGENT.md
- Confirmed that the new documentation accurately describes the test patterns used in the codebase
=> Update AGENT.md with test inheritance pattern and current viewer mocking documentation

AGENT.md, packages/app/__generated__/__isograph/Mutation/LoginAsDemoPerson/output_type.ts, packages/app/__generated__/__isograph/Mutation/LoginAsDemoPerson/resolver_reader.ts, packages/app/__generated__/__isograph/iso.ts, packages/app/mutations/LoginAsDemoPerson.tsx, packages/bfDb/models/BfPersonDemo.ts, packages/bfDb/models/__tests__/BfPersonDemo.test.ts, packages/graphql/graphqlContext.ts
- Extended BfPersonDemo class to support unique demo user setup with dedicated organization
- Updated documentation in AGENT.md with explanation of the demo user implementation
- Enhanced the organization creation process for demo users
- Manually verified demo user creation with unique organization
- Tested through the demo user login workflow
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/338).
* __->__ #338
* #337
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/338)
=> Add demo user organization creation to BfPersonDemo

packages/bfDb/bfDb.ts, packages/bfDb/bfDbBackend.ts, packages/bfDb/classes/__tests__/BfEdgeBaseTest.ts, packages/bfDb/classes/__tests__/BfNodeBaseTest.ts
- Fixed a type error in packages/bfDb/bfDb.ts related to error handling
- Added proper type checking when accessing error.message property
- Converted non-Error objects to strings when logging errors
- The type error that was causing the CI build to fail should be resolved
- Error handling in database cleanup is more robust
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/347)
=> Fix type error in database cleanup error handling

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedIn/LoggedInView.tsx, packages/bfDb/bfDbBackend.ts
- Added empty dependency array to useEffect in LoggedInView.tsx to prevent infinite redirects
- The missing dependency array was causing the redirect to execute on every render
- Verified that login redirect to /twitter now only happens once
- Ensured user navigation works correctly after the initial redirect
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/352).
* __->__ #352
* #351
=> Fix missing dependency array in LoggedInView useEffect hook

packages/app/__generated__/__isograph/Mutation/CreateVoice/entrypoint.ts, packages/app/__generated__/__isograph/Mutation/CreateVoice/param_type.ts, packages/app/__generated__/__isograph/Mutation/CreateVoice/resolver_reader.ts, packages/app/ai/getVoice.ts, packages/app/components/BfOrganization/EditIdentity.tsx, packages/app/mutations/CreateVoice.tsx, packages/graphql/__generated__/_nexustypes.ts, packages/graphql/__generated__/schema.graphql, packages/graphql/types/graphqlBfOrganization.ts
- Updated the onClick handler of the "Use the first version" button to set showChanges to false instead of true
- The button should return to the original view, not maintain the edit state
- Verified the button now correctly returns to the original view
- Tested in the identity editor interface
=> Fix "Use the first version" button functionality in EditIdentity component

infra/bff/friends/ai.bff.ts
This commit improves the user input handling mechanism in the `getYesNoInput` function by reading the entire line from stdin instead of a single character. This change addresses potential issues with reading partial input, ensuring that the input is fully captured and interpreted correctly. Additionally, the command for submitting pull requests has been updated to include the `pr` subcommand, which is necessary for the correct execution of the pull request submission. These changes enhance the robustness and reliability of the commit and pull request processes.
1. Test `aiCommit` and `aiAmend` flows to ensure they correctly interpret user input for commit message approval.
2. Verify that the pull request submission command executes correctly by checking for successful PR creation.
3. …
=> Enhance user input handling and PR submission command

.replit, apps/internalbf/internalbf.ts
This commit introduces a new application `internalbf` by adding a new file `internalbf.ts` under `apps/internalbf/`. The application is a simple server written in TypeScript, utilizing Deno. It logs incoming requests and responds with "Hello World". The server defaults to port 5000, configurable via the `PORT` environment variable. Additionally, the `.replit` configuration file has been updated to expose port 5000, enabling external access.
1. Ensure Deno is installed and available in the environment.
2. Run the `internalbf.ts` script using Deno: `deno run --allow-net --allow-env apps/internalbf/internalbf.ts`.
3. Verify the server starts successfully and logs the start message.
4. Send an HTTP request to `http://localhost:5000` and confirm that the response is "Hello World".
5. Check the …
=> Add internalbf app with basic server and port configuration

infra/bff/friends/land.bff.ts
This commit removes the code that runs CI checks before proceeding with a commit in the `land.bff.ts` file. The previous implementation included a sequence where CI checks were executed, and their result would determine whether the commit process would continue. This mechanism is now deemed redundant or unnecessary for the current workflow, hence its removal. Instead, the process now logs a straightforward message indicating that it is proceeding with the commit without executing the CI checks.
1. Ensure that the code compiles without errors after the removal of the CI check logic.
2. Verify the logging output to confirm that the message "Proceeding with commit" appears as expected.
3. Conduct a mock commit to ensure that the removal of CI checks does not affect the commit process …
=> Remove redundant CI checks before committing

.github/workflows/ci.yml, .replit, agents/behaviors/coding.bhc.md, apps/bfDs/components/__tests__/BfDsCheckbox.test.tsx, apps/boltFoundry/__tests__/e2e/home.test.e2e.ts, deno.lock, infra/bff/friends/ci.bff.ts, infra/bff/friends/e2e.bff.ts, infra/bff/friends/test.bff.ts, infra/docs/e2e-testing/0.1/version-0.1-implementation-plan.md, infra/docs/e2e-testing/project-plan.md, infra/testing/e2e/setup.ts, infra/testing/e2e/tests/home.test.ts, package.json, replit.nix
This commit introduces significant enhancements to the end-to-end (E2E) testing setup. Key changes include the installation of Chromium in the CI workflow to facilitate headless browser testing, the addition of a new E2E test for the home page, and improvements in the test setup and teardown processes. The `.replit` configuration file is updated to include a new workflow for running E2E tests. Additionally, the `ci.bff.ts` and `e2e.bff.ts` scripts are updated to include a step for running E2E tests, with improved logging and error handling. The tests now support taking and organizing screenshots for better debugging and test verification. An outdated home page test file has been deleted to avoid redundancy.
1. Verify that the CI pipeline executes successfully, including the new Chromium …
=> Add E2E test setup with Chromium installation and screenshot support

.github/workflows/ci.yml
This commit updates the GitHub Actions CI workflow to include a new step that uploads end-to-end (E2E) test screenshots as artifacts. The step is configured to execute regardless of the success or failure of previous steps, ensuring that screenshots are always available for review. The uploaded screenshots are named with the current GitHub run ID and will be retained for 5 days. This change facilitates better diagnostics and debugging by providing visual evidence of test results.
1. Trigger a CI run and ensure the workflow executes successfully.
2. Verify that the new "Upload test screenshots" step runs, even if prior steps fail.
3. Check the Actions tab in GitHub to confirm the screenshots are uploaded as expected.
4. Ensure that the artifacts are named correctly using the …
=> Add upload step for E2E test screenshots in CI workflow

.github/workflows/publish-dev.yml
This change modifies the GitHub Actions workflow for the `publish-dev` job to include the configuration of the npm authentication token. Specifically, it echoes the npm auth token into the `.npmrc` file within the development shell environment. This is necessary to authenticate with the npm registry before publishing the package. Without this step, attempts to publish to npm could fail due to missing authentication information. The change ensures that the `NODE_AUTH_TOKEN` environment variable is used to authorize the `npm publish` command, enabling successful publication to the npm registry under the 'dev' tag.
1. Verify that the `publish-dev` workflow runs successfully in a GitHub Actions environment.
2. Ensure that the step involving `npm publish` does not fail due to authentication …
=> Add npm auth token configuration for dev package publishing

.github/workflows/publish-dev.yml, .github/workflows/publish-release.yml
This commit updates the GitHub workflows for both development and release processes, ensuring that the version number is updated in the `deno.jsonc` file in addition to the `npm` package version. For the development workflow, the version is appended with a `-dev` suffix followed by the short SHA of the commit. For the release workflow, the version is set to the input version provided during the release process. This change ensures consistency in version tracking across different files and aligns the versioning in `deno.jsonc` with `npm`.
1. Trigger the development workflow and verify that the `deno.jsonc` version is correctly updated with the `-dev` suffix and the commit SHA.
2. Trigger the release workflow with a specific version input and confirm that `deno.jsonc` reflects this version. …
=> Update versioning in deno.jsonc for dev and release workflows

.github/workflows/publish-dev.yml
The Deno script used to update the version in the `deno.jsonc` file within the `publish-dev.yml` GitHub Actions workflow has been corrected. The previous implementation used an incorrect syntax for the inline JavaScript execution with Deno, specifically around the inline string template and the JSON file handling. This fix addresses the syntax issue by ensuring the correct use of the `--eval` flag and removing redundant backticks in the `console.log` statement, which could have led to runtime errors and incorrect version logging during the workflow execution.
1. Trigger the `publish-dev.yml` workflow manually in a development branch to ensure the workflow runs without errors.
2. Verify that the console output correctly logs the updated version string from `deno.jsonc`.
3. Check the …
=> Fix Deno script syntax for version update in publish workflow

.github/workflows/publish-dev.yml
The GitHub Actions workflow file `publish-dev.yml` was modified to simplify the command used for updating the version in the `deno.json` file. The previous command used `deno run -A --unstable --eval` to execute an inline script, which has been replaced with `deno eval -A`. This change makes the script execution more straightforward by using the `eval` subcommand directly, thereby removing the unnecessary `--unstable` flag and making the command cleaner and easier to read.
1. Trigger the `publish-dev.yml` GitHub Actions workflow.
2. Ensure that the workflow executes without errors.
3. Verify that the version in `deno.json` is updated correctly with the new format including `-dev.${{ env.sha_short }}`.
4. Confirm that no functionality is broken by running the associated tests for the …
=> Simplify Deno version script in GitHub Actions workflow

.github/workflows/publish-dev.yml
This commit changes the method of updating the version in the `deno.json` file within the GitHub Actions workflow for publishing development builds. Instead of using `deno eval` to parse and update the JSON file, the workflow now employs `jq` to accomplish this task. The version is extracted, incremented with the `-dev` suffix and the short SHA, and then written back to `deno.json`. This change enhances the readability and maintainability of the script by leveraging `jq`, a powerful tool for processing JSON.
1. Trigger the GitHub Actions workflow with this change.
2. Ensure that the `deno.json` file version is correctly updated to include the `-dev` suffix and the short SHA.
3. Verify that the workflow completes successfully without errors.
4. Manually inspect the `deno.json` file in the …
=> Switch version update in deno.json from Deno eval to jq

.github/workflows/publish-dev.yml, packages/bolt-foundry/deno.json
This commit modifies the GitHub Actions workflow `publish-dev.yml` by changing the workflow trigger from `push` to `pull_request`. This alteration ensures that the workflow runs on pull request events, facilitating better integration testing before merging into the main branch. Additionally, a debug command `ls -la` has been added to list directory contents in the `bolt-foundry` package directory. This command aids in troubleshooting by providing visibility into the files present when the workflow is executed.
1. Open a new pull request to the repository.
2. Verify that the `publish-dev.yml` workflow is triggered by the pull request.
3. Check the workflow logs to ensure the `ls -la` command outputs the expected directory listing.
4. Confirm that the version update logic in `deno.json` …
=> Switch publish trigger to pull_request and add debug listing

packages/bolt-foundry/bin/dnt.ts
This commit updates the generated `package.json` file to correct the paths for the `main`, `module`, and `exports` fields by including the `src` directory. The paths were previously pointing directly to the `script` and `esm` directories, which caused issues when trying to import or require modules. By appending `/src/` to these paths, it ensures that the correct files are referenced, allowing for proper resolution of modules in environments that rely on these fields.
1. Run the build process to generate the `package.json`.
2. Verify that the `main`, `module`, and `exports` fields in `package.json` now include the `src` directory in their paths.
3. Import and require modules as specified in the `package.json` to ensure that they are correctly resolved and no path-related errors occur.
- - …
=> Fix module path in generated package.json for src inclusion

apps/graphql/types/graphqlJoinWaitlist.ts, infra/bff/friends/build.bff.ts
This commit updates the API endpoint URL in `graphqlJoinWaitlist.ts` and `build.bff.ts` from `bf-cms.replit.app` to `bf-contacts.replit.app`. This change is likely made to reflect a backend service update or reorganization.
1. Ensure that the application builds successfully without errors.
2. Verify that requests to the updated endpoint are functioning as expected.
3. Monitor logs for any warnings or errors related to the updated API endpoints.
=> Update API endpoints and dependency versions

agents/behaviors/technical-implementation-versions.bhc.md
This change updates the naming convention for implementation plan documents within the technical implementation versioning guidelines. Previously, each versioned implementation plan file included the version number in its filename. This has been simplified so that all implementation plan files within version-specific directories are now named `implementation-plan.md`. The document headers will still include the version information to maintain clarity. This change ensures consistency across files and reduces redundancy in filenames. Additionally, the example directory structure and related references in the documentation have been updated to reflect this new naming convention.
1. Verify that all version directories contain the updated `implementation-plan.md` file.
2. Confirm that the …
=> Simplify naming convention for implementation plan documents

apps/boltFoundry/components/BfCurrentViewer/Home.tsx, apps/contacts/server.ts, apps/contacts/server/index.ts, apps/contacts/server/services/email.ts, apps/graphql/types/graphqlJoinWaitlist.ts, apps/web/routes/routeRegistry.ts, infra/bff/friends/build.bff.ts
This commit introduces several key changes across multiple files:
1. **Port Configuration**: The default server port has been changed from 5000 to 9999 in `server.ts`, `index.ts`, and `email.ts`. This ensures consistency across the server configuration and aligns with the intended deployment setup.
2. **Error Handling Improvement**: An early return was added in `Home.tsx` when the `joinWaitlist` fails, preventing further execution and potential errors.
3. **Dynamic URL Configuration**: The base URL in `graphqlJoinWaitlist.ts` is now dynamically set based on the environment, switching between a production URL and a localhost URL for development purposes.
4. **New Route Handler**: A new route `/contacts-cms` was added in `routeRegistry.ts` to forward requests to an external API. This route …
=> Update server port and configure new route handler

.github/workflows/ci.yml, .github/workflows/publish-dev.yml, .github/workflows/publish-release.yml
This commit introduces caching for `node_modules` and `vendor` directories across multiple GitHub Actions workflows (`ci.yml`, `publish-dev.yml`, and `publish-release.yml`). The caching is implemented using the `actions/cache@v4` action to speed up job execution by reusing previously built dependencies. The cache key is generated based on the operating system and the hash of package lock files to ensure cache validity. The changes aim to optimize build times by avoiding redundant installations of dependencies.
1. Trigger the `ci.yml`, `publish-dev.yml`, and `publish-release.yml` workflows to ensure they run successfully with caching enabled.
2. Verify that cache is being stored and retrieved correctly by checking the GitHub Actions logs for cache hit/miss information.
3. Confirm that …
=> Add caching for node_modules and vendor directories in CI workflows

infra/bff/friends/build.bff.ts
This change introduces a new step in the build process for the friends module within the infra/bff directory. Specifically, it adds a build command for the "bolt-foundry" package. The build script now logs memory usage around this process if debugging is enabled, providing insight into resource utilization during the build. If the build process for bolt-foundry fails, an error is logged, and the process exits early with the corresponding error code. This ensures that the build process does not proceed with an incomplete or failed build of the bolt-foundry package, thus maintaining the integrity and reliability of the overall build process.
1. Run the updated build script with debugging enabled to ensure memory usage is logged before and after the bolt-foundry build.
2. Verify that a …
=> Add bolt-foundry package build process to build script

apps/collector/__tests__/collector.test.ts, apps/collector/collector.ts
This commit introduces a new mechanism to detect and log Bolt Foundry (BF) requests by checking for a specific API key in the request headers. The code now distinguishes BF requests from other JSON requests by verifying the presence of the `x-bf-api-key` header along with the `application/json` content type. When a BF request is identified, the system logs the API key with an info-level log and the data payload with a debug-level log. Non-BF requests still log their payload as text, but this is now done at the debug level instead of info level, allowing for cleaner log management and improved monitoring of specific BF requests.
1. Send a request with `content-type` set to `application/json` and the `x-bf-api-key` header included, and verify that the log records the API key and payload at …
=> Enhance request logging and add BF API key detection

.gitignore, apps/collector/__tests__/llm-event-tracker.test.ts, apps/collector/collector.ts, apps/collector/llm-event-tracker.ts, deno.jsonc, deno.lock, infra/bff/friends/land.bff.ts, packages/bolt-foundry/bolt-foundry.ts
This commit introduces functionality to merge a `.replit.local.toml` file into the existing `.replit` file. The `.gitignore` is updated to ignore `.replit.local.toml`. The `deno.jsonc` and `deno.lock` files are modified to include the `@std/toml` module, enabling TOML parsing and stringifying. Additionally, a deep merge function is implemented to handle merging of complex TOML structures, ensuring proper handling of nested objects and arrays, with special treatment for workflow arrays to prevent duplicates.
The removal of the `@denosaurs/python` dependency and associated entries in the lock file is also included, likely due to it no longer being required for the project.
1. Verify that `.replit.local.toml` is correctly ignored by git.
2. Place a `.replit.local.toml` file with desired …
=> Add support for merging .replit.local.toml into .replit

.github/workflows/publish-dev.yml
This commit modifies the GitHub Actions workflow file `publish-dev.yml` to streamline the execution of the build script. Previously, there was a redundant `cd` command to navigate into the `packages/bolt-foundry` directory before running the Deno build script. This commit removes the `cd` command and directly runs the Deno script with the full path `packages/bolt-foundry/bin/build.ts`, simplifying the script and potentially reducing errors related to directory navigation.
1. Trigger the GitHub Actions workflow using the modified `publish-dev.yml`.
2. Verify that the build process for `bolt-foundry` executes successfully without errors.
3. Ensure that the output and artifacts from the build process are consistent with previous successful runs.
4. Confirm that the workflow continues to the …
=> Simplify build script path in GitHub Actions workflow

.gitignore
This commit updates the `.gitignore` file to include `generated-icon.png`, ensuring that this file is ignored by Git. The addition of this file to `.gitignore` indicates that `generated-icon.png` is likely a dynamically generated or temporary file that should not be tracked in version control. Additionally, there is a change in the `generated-icon.png` binary file itself, but these changes are not detailed in the diff output. This update helps maintain a clean repository by preventing unnecessary files from being committed.
1. Verify that after this change, `generated-icon.png` is not tracked by Git.
- Run `git status` to ensure `generated-icon.png` does not appear in the list of changed files.
2. If `generated-icon.png` was previously committed, ensure it is removed from the repository …
=> Add generated-icon.png to .gitignore

docs/wut.md
This update introduces a new section titled "Cards" in `docs/wut.md`. The section provides a definition and explanation of what cards are, listing their components such as a title, a summary, and a hierarchical set of rules. It clarifies that cards are designed to be understood by both humans and machines and are used to reinforce and clarify specific principles by linking them to samples.
1. Review the rendered Markdown in `docs/wut.md` to ensure the new "Cards" section appears correctly and coherently.
2. Verify that the explanation of cards is clear and understandable.
3. Ensure there are no formatting errors in the Markdown file after the addition.
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" …
=> Add section on Cards to documentation

infra/bff/friends/land.bff.ts
This change reorders the process of creating a git commit and merging the `.replit.local.toml` file with `.replit`. Previously, the git commit was attempted before checking for the presence of `.replit.local.toml` and performing a merge if it existed. The logic has been adjusted so that the check and potential merge of `.replit.local.toml` occur before the git commit is attempted. This ensures that the merge step is always executed, regardless of whether the commit succeeds or fails, providing a more robust and predictable workflow.
1. Verify that the `.replit.local.toml` merge step is executed before the git commit.
2. Test with a project that includes a `.replit.local.toml` file and ensure the merge with `.replit` occurs correctly.
3. Confirm that the git commit is performed …
=> Reorder git commit to follow .replit.local.toml merge

infra/bff/friends/land.bff.ts
The logic for handling array merging in the `land.bff.ts` file has been simplified. Previously, arrays from the `target` and `source` were combined, and duplicates were removed by converting the combined array into a `Set`. Now, the logic has been changed to directly use the array from the `source`, eliminating the need to merge arrays and handle duplicates. This change reduces complexity and improves performance by avoiding unnecessary operations.
1. Run existing unit tests to ensure no regressions occur due to the change in array handling.
2. Create tests that specifically check scenarios where arrays are involved to verify that the `source` array is correctly used.
3. Test with mock data that includes arrays to confirm the new behavior aligns with expectations, ensuring the `target` …
=> Simplify array merging logic in land.bff.ts

apps/bfDb/coreModels/BfNode.ts, apps/bfDb/storage/storage.ts
This commit introduces a new storage façade to streamline database operations in the `BfNode.ts` file. The changes involve creating a new module, `storage.ts`, under `apps/bfDb/storage/`, which serves as a temporary façade for existing database helper functions. The primary goal is to abstract the database interaction logic and prepare for potential future refactoring or adapter swaps. The functions `bfGetItem`, `bfPutItem`, and `bfQueryItemsUnified` are replaced with `storage.get`, `storage.put`, and `storage.query`, respectively.
The introduction of `storage.ts` encapsulates the database operations, making it easier to maintain and alter the underlying database logic without affecting the rest of the codebase. The changes are specifically implemented in `BfNode.ts` to utilize this new …
=> Refactor BfNode.ts to use a storage façade

apps/bfDb/classes/BfEdgeBase.ts, apps/bfDb/classes/BfNodeBase.ts, apps/bfDb/coreModels/BfNode.ts, apps/bfDb/utils/metadata.ts
This commit refactors the metadata generation logic for nodes and edges into standalone utility functions located in `apps/bfDb/utils/metadata.ts`. The refactored functions, `generateNodeMetadata` and `generateEdgeMetadata`, encapsulate the logic for creating metadata, making it reusable across different classes. The changes also involve updating existing classes to use these utility functions instead of inline logic.
For `BfEdgeBase`, the `generateEdgeMetadata` method was simplified by delegating to the new utility function, enriching the resulting metadata with the class name. Similarly, in `BfNodeBase`, the `generateMetadata` method now uses `generateNodeMetadata` and allows subclasses to customize the `sortValue` property.
In `BfNode`, the internal properties handling was also …
=> Refactor metadata generation into utility functions

apps/bfDb/classes/BfNodeBase.ts, apps/bfDb/coreModels/BfNodeInMemory.ts, apps/bfDb/graphql/helpers.ts
This commit refactors the `BfNodeBase` class and its related components to streamline the conversion of node instances to their GraphQL representations and improve the handling of GraphQL connections. Key changes include:
1. **GraphQL Conversion Refactor**: The `toGraphql` method in `BfNodeBase` has been simplified by offloading the conversion logic to a new utility function `toGraphqlFromNode` in the newly created `graphql/helpers.ts` module. This enhances code maintainability and reuse.
2. **Relay Connection Logic Update**: The `queryTargetsConnectionForGraphql` method in both `BfNodeBase` and `BfNodeInMemory` now leverages the new `connectionFromNodes` function to construct GraphQL Relay connections. This change is aimed at unifying the connection creation logic and removing redundant …
=> Refactor GraphQL conversion and connection logic in BfNodeBase

.github/workflows/ci.yml, infra/bff/friends/build.bff.ts, infra/bff/friends/ci.bff.ts, infra/bff/friends/land.bff.ts
This commit introduces a new optional build step for the bolt-foundry package within the CI and BFF scripts. A new command-line argument, `--include-bolt-foundry`, has been added to both the `ci.yml` workflow and the `build.bff.ts` script. When this flag is specified, the bolt-foundry package will be built; otherwise, the step will be skipped. This change is intended to improve build efficiency by only including the bolt-foundry build when necessary. Additionally, the `ci.bff.ts` and `land.bff.ts` scripts have been updated to accommodate this new argument, allowing for more granular control over build processes in different environments.
1. Run the CI workflow without the `--include-bolt-foundry` flag and verify that the bolt-foundry package build step is skipped.
2. Run the CI workflow …
=> Add optional bolt-foundry build step in CI and BFF scripts

.github/workflows/ci.yml, infra/bff/bff.ts, infra/bff/friends/build.bff.ts, infra/bff/friends/ci.bff.ts, infra/bff/friends/land.bff.ts, infra/bff/posthogTracker.ts
This commit introduces analytics tracking for BFF (Bolt Foundry Friend) commands using PostHog. The `help` command and other BFF commands are now wrapped to log their execution details such as command name, options, success status, and execution duration. A new module `posthogTracker.ts` was added to handle the initialization and tracking logic. This includes reading user details from a local file or fetching from the GitHub API if necessary, and sending the captured data to PostHog. The analytics are designed not to interfere with the normal operation of the BFF commands, ensuring robust command execution.
1. Ensure the PostHog API key is configured correctly in the environment.
2. Run the BFF `help` command and verify that it executes without errors.
3. Check the PostHog dashboard to …
=> Add PostHog analytics tracking to BFF commands

apps/collector/collector.ts
The `getCurrentViewerApiKey` function has been removed from the `collector.ts` file as it was no longer needed. Previously, this function was used to fetch an API key from the environment variables, defaulting to "anon" if not set. The code now directly uses `bfApiKey` as the `distinctId` when capturing events with `appPosthog`, making the `getCurrentViewerApiKey` function redundant. This change simplifies the code by eliminating unnecessary function calls and environment variable dependencies.
1. Ensure the application builds successfully without errors.
2. Verify that the collector service runs without issues.
3. Test the `collector:ingest` event capturing to confirm it uses `bfApiKey` as the `distinctId`.
4. Check logs to ensure no references to `getCurrentViewerApiKey` are executed or …
=> Remove unused getCurrentViewerApiKey function

apps/collector/collector.ts
The event name for data collection within the `collector.ts` file has been changed from "collector:ingest" to "sample collected". This update aims to provide a more descriptive and human-readable event name, aligning with the naming conventions used across the application for better clarity and consistency when tracking events in analytics.
1. Run the application and trigger a data collection event.
2. Verify that the event is logged with the new name "sample collected" in the analytics tool.
3. Ensure no other functionalities are affected by this change by running existing tests and checking for any failures.
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" …
=> Update event name for data collection in collector.ts

docs/product-plan.md
This commit adds a new document, `product-plan.md`, to the `docs/0.2/` directory, outlining the BF Product Plan for 2025. The document details the objective of improving customers' LLM capabilities through an evaluation and observability pipeline. Key milestones are defined from 0.0 to 0.6, outlining stages such as metrics integration, structured prompt generation, identity and behavior card generation, reconciliation of samples, and backtesting. The plan also specifies out-of-scope items like a lightweight experimentation framework, and defines success metrics focusing on reconciled samples.
1. Verify that the new document `product-plan.md` exists in the `docs/0.2/` directory.
2. Read through the document to ensure clarity and completeness of the product plan details.
3. Check for …
=> Add BF Product Plan 2025 to documentation

infra/bff/friends/e2e.bff.ts, infra/testing/e2e/setup.ts
This commit introduces a utility function `waitForPort` in `e2e.bff.ts` to ensure that the server is ready and available on a specified port before proceeding with tests. This replaces the previous fixed wait time, improving reliability in different environments. Additionally, in `setup.ts`, the headless mode for end-to-end tests can now be configured using the `BF_E2E_HEADLESS` environment variable, allowing greater flexibility for test executions.
1. Run the end-to-end tests and verify that the server starts correctly and tests execute without premature failures.
2. Modify the `BF_E2E_HEADLESS` environment variable to `false` and ensure that the tests run in non-headless mode.
3. Test the `waitForPort` function by starting the server on a different port and observe the timeout warning …
=> Add port availability check and config-based headless mode

apps/contacts/server/routes.ts
This commit introduces a dry run mode to the contact creation endpoint in `routes.ts`. When a contact is submitted with an email address ending in `.dryrun@example.com`, the server will recognize it as a dry run request. In this mode, the contact data is validated, but the information is not stored in the database. Instead, a simulated success response is sent back to the client with the contact details and an additional `dryRun` flag set to `true`. This feature allows testing of the endpoint without affecting the actual data in the database.
1. Submit a contact creation request with a valid email ending in `.dryrun@example.com`.
- Verify that the request logs "Dry run detected - skipping database save".
- Ensure the response status is 200 and includes the correct contact data with …
=> Add dry run mode for contact creation endpoint

apps/bfDb/classes/CurrentViewer.ts, apps/bfDb/graphql/__generated__/_nexustypes.ts, apps/bfDb/graphql/__generated__/schema.graphql, apps/bfDb/graphql/builder/__tests__/fromSpec.test.ts, apps/bfDb/graphql/builder/fromSpec.ts
This commit introduces several changes to the GraphQL schema and related TypeScript classes. The `CurrentViewerLoggedIn` and `CurrentViewerLoggedOut` classes were modified by removing the unused `gqlSpec` static property. Correspondingly, new root types and field return types for these classes were added in the GraphQL schema definitions to reflect their presence in the GraphQL API. Additionally, new mutations `loginWithEmailDevCurrentViewerLoggedIn` and `loginWithEmailDevCurrentViewerLoggedOut` were added to the `Mutation` type, allowing for separate handling of logged-in and logged-out viewers.
The `fromSpec.ts` file was updated to ensure that mutations are only emitted for the class that owns the spec, preventing subclasses from unintentionally exposing parent mutations. This change …
=> Enhance GraphQL schema with CurrentViewer types and mutations

apps/bfDb/classes/CurrentViewer.ts, apps/bfDb/graphql/GraphQLObjectBase.ts, apps/bfDb/graphql/__generated__/_nexustypes.ts, apps/bfDb/graphql/__generated__/schema.graphql
This commit enhances the GraphQL schema by introducing support for two new types: `CurrentViewerLoggedIn` and `CurrentViewerLoggedOut`. The `CurrentViewer` class and its subclasses now utilize `defineGqlNode` to specify their GraphQL specifications. The `GqlNodeSpec` type has been adjusted to allow `undefined` values, accommodating scenarios where the GraphQL specification is not explicitly defined. The generated GraphQL types and the schema have been updated to include these new types along with their respective fields (`email` and `id`). Additionally, new mutations have been added to facilitate login operations for both `CurrentViewerLoggedIn` and `CurrentViewerLoggedOut`.
1. Verify that the GraphQL schema includes the new `CurrentViewerLoggedIn` and `CurrentViewerLoggedOut` types with …
=> Add GraphQL support for CurrentViewerLoggedIn and LoggedOut types

apps/boltFoundry/server/components/ServerRenderedPage.tsx, apps/web/web.tsx, packages/get-configuration-var/get-configuration-var.ts
This commit introduces several key changes across the codebase:
1. **PostHog Integration**: Added a script to initialize PostHog analytics in `ServerRenderedPage.tsx`. The script ensures PostHog is only initialized if the `POSTHOG_API_KEY` is available in the environment. This integration helps in tracking user interactions and gaining insights into user behavior.
2. **startAutoRefresh Enhancement**: Updated the `startAutoRefresh` function in `get-configuration-var.ts` to return a promise. This change involves wrapping the initial secret refresh calls in a `Promise.allSettled`, ensuring that the auto-refresh process can be awaited. Additionally, the function now returns an object that includes promise capabilities, allowing for better async handling.
3. **Await startAutoRefresh**: …
=> Integrate PostHog and Enhance AutoRefresh with Promises

apps/boltFoundry/entrypoints/EntrypointHome.ts
This change updates the title on the EntrypointHome component from "Bolt Foundry: The Content Operating System." to "Bolt Foundry: Unit Tests for LLMs.". This update is likely intended to reflect a recent focus or feature enhancement related to unit tests for large language models (LLMs) within the Bolt Foundry application. The title change helps align the user interface with the latest development focus or marketing message.
1. Verify that the homepage title displays "Bolt Foundry: Unit Tests for LLMs.".
2. Run any existing automated tests to ensure that this change does not introduce regressions:
```bash
./run_tests.sh
```
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" …
=> Update homepage title to reflect new LLM unit tests

.claude/settings.local.json, infra/bff/friends/merge.bff.ts
Update merge command to use rebase as the default merge method since that's
the only allowed method in the repository. Also add support for automatically
closing dependent PRs in a stack after merging.
Changes:
- Change default merge method from squash to rebase
- Add --close-stack (-s) flag to automatically close dependent PRs after merging
- Refactor code to separate API calls for better reusability
- Add support for detecting and closing stacked PRs based on branch relationships
- Update help text to document the new functionality
Test plan:
1. Run 'bff merge PR_NUMBER' - should merge with rebase
2. Run 'bff merge PR_NUMBER --close-stack' - should merge and close dependent PRs
3. Run 'bff merge' - should show updated help text
4. Run 'bff lint' - should pass with no errors
=> Update bff merge to use rebase by default and handle stacked PRs

packages/get-configuration-var/__tests__/get-configuration-var.test.ts
- test getSecret with unknown key missing from ENV
- `./infra/bin/bff ci` *(fails: `/usr/bin/env: ‘deno’: No such file or directory`)*
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/780)
=> Add undefined case test for getSecret

apps/bfDb/docs/0.2/implementation-plan.md
Update the v0.2 implementation plan with several important corrections:
- Clarify that interfaces should NOT be in a separate directory
- Remove redundant __typename field definition (auto-added by GraphQL)
- Update import paths to always use full filenames with extensions
- Replace 'any' type with specific AnyGraphqlObjectBaseCtor
- Improve error handling in resolveType to throw instead of return "Unknown"
These changes ensure the implementation follows GraphQL best practices
and project conventions for importing, type safety, and error handling.
=> Fix GraphQL Node Interface implementation plan

apps/bfDb/docs/0.3/implementation-plan.md, apps/bfDb/docs/status.md
Streamline the implementation plan for v0.3 to focus solely on ensuring
GraphQL interfaces are properly registered and loaded.
Changes:
- Simplify implementation steps to focus on minimal changes
- Remove complex registry and validation features (deferred to v0.4)
- Update status.md to reflect simplified approach
- Keep technical design minimal and focused
=> Simplify GraphQL Builder v0.3 Implementation Plan

apps/bfDb/bin/genBarrel.ts, apps/bfDb/classes/BfNode.ts, apps/bfDb/classes/GraphQLNode.ts, apps/bfDb/classes/__generated__/classesList.ts, apps/bfDb/docs/0.3/implementation-plan.md, apps/bfDb/docs/status.md, apps/bfDb/graphql/__generated__/_nexustypes.ts, apps/bfDb/graphql/__generated__/interfacesList.ts, apps/bfDb/graphql/__generated__/schema.graphql, apps/bfDb/graphql/__tests__/InterfaceLoading.test.ts, apps/bfDb/graphql/graphqlInterfaces.ts, apps/bfDb/graphql/interfaces/GraphQLNode.ts, deno.lock, package.json
Add decorator-based GraphQL interface detection and registration system to ensure interfaces are properly loaded in the schema regardless of their location in the codebase.
Changes:
- Add GraphQLNode class with Node interface implementation
- Implement GraphQLInterface decorator for marking interface classes
- Update genBarrel.ts to detect @GraphQLInterface decorated classes
- Enhance loadInterfaces function with improved logging and detection
- Add InterfaceLoading.test.ts to verify decorator-based interface detection
- Add v0.3 implementation plan with approach and technical design
- Update status.md to track v0.3 progress
Test plan:
1. Run bff test apps/bfDb/graphql/__tests__/InterfaceLoading.test.ts
2. Verify tests pass for interface detection and registration
3. Confirm GraphQL …
=> Implement GraphQL v0.3 with interface decorator detection

cards/behaviors/copy-editing.bhc.md, cards/personas/copy-editor.pcd.md
Implement standardized copy editing process with behavior card protocol
and persona card for maintaining editorial consistency.
Changes:
- Added cards/behaviors/copy-editing.bhc.md with complete editing workflow
- Added cards/personas/copy-editor.pcd.md with style guidelines and traits
- Updated .claude/settings.local.json to allow bff commands
Test plan:
1. Verify behavior card follows established protocol structure
2. Check persona card includes specific style guidelines
3. Confirm copy editing process is actionable and measurable
=> Add copy editing behavior and persona cards

packages/bolt-foundry/builders/__tests__/assistantApi.test.ts, packages/bolt-foundry/builders/builders.ts
- Add boltFoundryClient.createAssistant() public API
- Create SpecForAssistant class (renamed from AssistantSpec)
- Create SpecBuilderForAssistant immutable builder
- Add PersonaBuilder and ConstraintsBuilder scaffolds
- Implement render() method with OpenAI format output
- Add proper option merging for user-provided parameters
- Create minimal test suite (3 tests, all passing)
- Fix all lint issues for clean codebase
Phase v0.0.2.2 ~40% complete - scaffold working, need to implement:
- Persona/constraints data storage
- XML persona card generation
- True builder immutability
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/886).
* #891
* #890
* #889
* #888
* …
=> feat(bolt-foundry): implement assistant API scaffold with TDD approach

docs/product-plan.md
- Insert docs project as first alpha milestone (v0.1)
- Renumber subsequent versions (CLI becomes 0.2, GUI becomes 0.3, etc.)
- Focus on problem-solving examples and interactive demos
- Goal: Enable self-serve understanding and reduce 1:1 explanations
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/907)
=> Add interactive documentation as v0.1 in alpha roadmap

docs/STATUS.md, docs/getting-started.mdx, docs/product-plan.md, docs/quickstart.mdx, examples/README.md
- Updated installation instructions and import statements across documentation
- Fixed package references in quickstart, getting-started, product-plan, examples README, and status docs
- Corrected NPM package link in STATUS.md
Fixes #1019
Co-authored-by: justicart <justicart@users.noreply.github.com>
=> fix: update npm library references from @bolt-foundry/sdk to @bolt-foundry/bolt-foundry

infra/bff/friends/amend.bff.ts, infra/bff/friends/commit.bff.ts
Update both bff commit and bff amend to use the full bff precommit
command instead of partial or minimal checks.
Changes:
- bff commit: Replace inline format/lint/check with bff precommit
- bff amend: Replace format-only with full bff precommit
- Both commands now use --skip-precommit flag (was --skip-pre-check)
- Precommit runs by default, includes staging, format, lint --fix, check, test
Benefits:
- Consistent pre-commit behavior across all commit operations
- Automatic staging of new/deleted files
- Full test suite runs before commits
- Single source of truth for pre-commit logic
Test plan:
- Run bff commit with and without --skip-precommit
- Run bff amend with and without --skip-precommit
- Verify all checks run in correct order
- Verify --no-submit still works as expected
=> Integrate full precommit checks into commit and amend commands

.github/workflows/publish-aibff-release.yml, README.md, deno.jsonc, infra/appBuild/plugins/denoFileResolver.ts, infra/bff/friends/eval.bff.ts, infra/bff/friends/remote.bff.ts, infra/bff/shellBase.ts, package.json, packages/logger/logger.ts, packages/logger/terminalSpinner.ts
- Replace chalk npm dependency with @std/fmt/colors from JSR
- Add println method to Logger interface for external output
- Move terminalSpinner from lib/ to logger package
- Update esbuild configuration to handle JSR imports using @deno/cache-dir
- Export startSpinner from logger.ts for unified imports
This refactoring removes the npm chalk dependency in favor of Deno's native
color support and consolidates terminal output functionality within the
logger package.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1106).
* #1110
* #1109
* #1108
* #1107
* __->__ #1106
* #1105
* #1104
* #1103
=> refactor(logger): replace chalk with @std/fmt/colors and add println method

apps/aibff/bin/build.ts, apps/aibff/bin/create-release-notes.ts, apps/aibff/bin/prepare-release.ts, apps/aibff/commands/rebuild.ts, apps/aibff/main.ts, apps/boltFoundry/__tests__/e2e/joinWaitlist.test.e2e.ts, deno.lock, infra/appBuild/plugins/denoFileResolver.ts
- Replace logger.info() with logger.println() for all user-facing output
- Replace logger.error() with logger.println(msg, { isError: true }) for errors
- Add spinner support for long-running operations (build, compile, etc.)
- Keep logger.debug() and logger.warn() for internal logging
- Follow the pattern established in eval.ts which already uses direct console output
- Fix denoFileResolver to handle both string and Uint8Array content types
This makes the CLI output cleaner and more suitable for piping/scripting
by removing timestamps and log level prefixes from user-facing messages.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1108).
* #1110
* #1109
* …
=> refactor(aibff): replace logger with println for user-facing output

apps/aibff/bin/build.ts, apps/aibff/bin/create-release-notes.ts, apps/aibff/bin/prepare-release.ts, apps/aibff/commands/rebuild.ts, apps/aibff/main.ts, packages/logger/__tests__/logger.test.ts, packages/logger/logger.ts
- Replace println options bag with two distinct methods
- println(message, stripColors?) for standard output
- printErr(message, stripColors?) for error output
- Update all aibff usage to use printErr for error messages
- Update tests to verify both methods work correctly
This provides a cleaner API that makes the intent more explicit
and properly separates stdout and stderr output.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1109).
* #1110
* __->__ #1109
=> refactor(logger): change println API to have separate println and printErr methods

.gitmodules
Adds internalbf-docs as a git submodule at memos/@internalbf-docs. This is part of the codebot workspace restructure to consolidate everything under @bfmono. The submodule is optional - OSS users will get an empty directory. Internal users can initialize with: git submodule update --init. Related: #1729
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1736)
=> Add @internalbf-docs as git submodule

.github/workflows/build-codebot-container.yml, infra/apps/codebot/Dockerfile, infra/apps/codebot/Dockerfile.debug, infra/apps/codebot/debug-docker-build.sh
- Fixes Docker build failures that were occurring during Nix installation
- Adds debugging capabilities to the GitHub Actions workflow for easier troubleshooting
- Improves build reliability by properly handling the Nix installation process
- **Workflow improvements** (`build-codebot-container.yml`):
- Added `workflow_dispatch` with options for manual triggering
- Added `debug_enabled` input for debug mode with tmate session
- Added `build_only` input to test builds without pushing
- Added `platform` selection to build for specific architectures
- Added verbose build output and failure diagnostics
- **Dockerfile improvements**:
- Enhanced Nix installation with better error handling
- Added fallback to official Nix installer if Determinate Systems installer fails
- Added …
=> fix: improve Docker build reliability with native ARM64 runners

infra/bft/tasks/codebot.bft.ts
The container's bashrc expects TERM to contain 'color' or '256color' to enable
color support, but it was only getting 'xterm'. This caused incorrect color
display in Claude Code within the container.
Also includes CODEBOT_CONTAINER=true from main branch to identify we're in a codebot container.
=> fix: add TERM=xterm-256color to codebot container for proper color support
