content/changelog/0.0.0.md
Summary:
first roadmap omg!
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/8)
=> First roadmap

.gitignore, .replit, deno.jsonc, infra/bff/friends/commit.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/15)
=> Unfreeze lockfile

.replit
Summary:
This makes it so it's simpler to see errors
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/21).
* #29
* #28
* #27
* #26
* #25
* #24
* #23
* #22
* __->__ #21
=> Sleep if the command fails

infra/bff/friends/build.bff.ts, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoginAndRegisterForm.tsx, packages/bfDb/models/BfPerson.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/46)
=> Fixes for prod

deno.jsonc, deno.lock, infra/bff/friends/build.bff.ts, package.json, packages/app/contexts/AppEnvironmentContext.tsx, packages/web/web.tsx
Posthog!
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/51)
=> feat(app): Posthog

infra/appBuild/appBuild.ts, infra/bff/friends/land.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/52)
=> fixes file resolution

infra/bff/friends/devTools.bff.ts, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoggedOutView.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/54).
* __->__ #54
* #53
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/54)
=> Add feature flag for try demo button

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoggedOutView.tsx, packages/web/web.tsx
Summary:
adds cache headers
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/55)
=> Fix caching

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoggedOutView.tsx, packages/app/contexts/AppEnvironmentContext.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/60)
=> Comment out posthog temporarily

experimental/aiYC.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/72)
=> Remove test data

.gitignore, .replit, content/documentation/quickstart.md, infra/bff/friends/devTools.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/81)
=> Dev tooling updates

infra/appBuild/appBuild.ts, infra/bff/friends/build.bff.ts, infra/bff/friends/commit.bff.ts, infra/bff/friends/db.bff.ts, infra/bff/friends/devTools.bff.ts, infra/bff/shellBase.ts, infra/bff/tools.ts, lib/ai.ts, packages/bfDb/bfDb.ts, packages/bfDb/bfDbUtils.ts, packages/bfDb/models/BfPerson.ts, packages/getConfigurationVariable.ts, packages/logger.ts, packages/web/web.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/83)
=> Get environment variables differently

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedIn/YcForm.tsx
=> Added spinner to button onSubmit

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedIn/YcForm.tsx
=> remove CF YC application data

deno.jsonc, deno.lock, infra/bff/friends/build.bff.ts, package.json, packages/app/pages/PageUIDemo.tsx, packages/app/routes.ts, packages/app/server/components/ServerRenderedPage.tsx, packages/bfDb/bfDbUtils.ts, packages/bfDs/components/BfDsDropzone.tsx, packages/graphql/types/graphqlBfCurrentViewer.ts, packages/tools/FinalCutProXML.tsx, packages/web/web.tsx, static/bfDsStyle.css, static/toolsStyle.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/58).
* __->__ #58
* #57
* #56
=> Add final cut pro xml tool

content/blog/Facebook-s-lack-of-storytelling-cost-billions-and-killed-the-brand.mdx, content/blog/test.mdx, content/blog/what-is-story-led-growth.md, deno.jsonc, deno.lock, infra/bff/friends/__tests__/contentLint.test.ts, infra/bff/friends/build.bff.ts, infra/bff/friends/commit.bff.ts, infra/bff/friends/contentLint.bff.ts, infra/bff/friends/createPerson.bff.ts, infra/bff/friends/db.bff.ts, infra/bff/friends/devTools.bff.ts, infra/bff/friends/fork.bff.ts, infra/bff/friends/land.bff.ts, infra/bff/friends/nix.bff.ts, infra/bff/friends/pull.bff.ts, infra/bff/friends/run.bff.ts, infra/bff/friends/testStack.bff.ts, infra/bff/shellBase.ts, packages/app/components/BfBlog/BlogFrame.tsx, packages/app/components/BfCurrentViewer/Blog.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/108).
* __->__ #108
* #107
* #106
* #105
* #104
* #103
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/108)
=> Content updates

infra/bff/__tests__/bff.test.ts, infra/bff/__tests__/bin_bff.test.ts, infra/bff/__tests__/shellbase.test.ts, infra/bff/friends/__tests__/build.test.ts, infra/bff/friends/__tests__/db.test.ts, infra/bff/friends/__tests__/fork.test.ts, infra/bff/friends/__tests__/mergeStack.test.ts, infra/bff/friends/__tests__/pull.ts, infra/bff/friends/__tests__/run.test.ts, infra/bff/friends/__tests__/testStack.test.ts, infra/bff/friends/mergeStack.bff.ts, infra/bff/shellBase.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/110).
* __->__ #110
* #109
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/110)
=> Scratch tests for bff commands

__TEMPLATE__ .md, __TEMPLATE__.mdx, content/blog/test.mdx, deno.lock, infra/bff/friends/__tests__/template.test.ts, infra/bff/friends/template.bff.ts, infra/bff/prompts/base.md
=> Creates a place for bff prompts (for assistants)

__TEMPLATE__ .md, __TEMPLATE__.mdx, content/blog/test.mdx, deno.lock, infra/bff/friends/__tests__/template.test.ts, infra/bff/friends/template.bff.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/114).
* __->__ #114
* #113
=> Adds a bff template command which lets you use templates

.replit, infra/bff/friends/__tests__/llm.test.ts, infra/bff/friends/llm.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/119)
=> Don't ingest binary files

.replit, infra/bff/friends/devTools.bff.ts, packages/web/tools.tsx, packages/web/web.tsx
Summary:
Play button is all you need now.
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/141)
=> Upgrade devtools experience.

infra/bff/friends/devTools.bff.ts, packages/web/tools.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/142)
=> Super upgrade dev tools

.replit, infra/bff/friends/devTools.bff.ts, packages/web/tools.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/145)
=> Proxy requests unless in the middle of a gh auth sesh

packages/web/tools.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/143)
=> Add click to copy button

packages/bfDb/models/BfBlogPost.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/144)
=> Allow loading blog posts without an extension

.replit, infra/bff/friends/build.bff.ts, packages/web/web.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/146)
=> Add web port to set port for deploy

content/documentation/community/changelog/company-updates/2025-02-17.md, content/documentation/community/changelog/company-updates/__TEMPLATE__.mdx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/173)
=> Weekly update

infra/bff/friends/pull.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/177)
=> Update bff pull

packages/app/entrypoints/EntrypointTwitterIdeatorEvents.ts, packages/web/web.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/178).
* #179
* __->__ #178
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/178)
=> Fix utf encoding issues

packages/app/AppRoot.tsx, packages/app/entrypoints/EntrypointTwitterIdeatorEvents.ts, packages/web/web.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/179).
* __->__ #179
* #178
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/179)
=> Rebuild the isograph thing when the path changes

content/documentation/community/changelog/company-updates/2025-02-17.md, infra/bff/friends/ci.bff.ts, infra/bff/friends/format.bff.ts, infra/bff/friends/lint.bff.ts, infra/bff/friends/pull.bff.ts, infra/bff/friends/restartLsp.bff.ts, packages/app/AppRoot.tsx, packages/app/contexts/RouterContext.tsx, packages/app/entrypoints/EntrypointTwitterIdeator.ts, packages/app/entrypoints/EntrypointTwitterIdeatorEvents.ts, packages/app/entrypoints/EntrypointTwitterIdeatorEventsPermalink.ts, packages/app/entrypoints/EntrypointTwitterIdeatorVoice.ts, packages/app/entrypoints/EntrypointTwitterIdeatorWorkshop.ts, packages/app/entrypoints/EntrypointTwitterIdeatorWorkshopPermalink.ts, packages/graphql/types/graphqlBfOrganization.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/180)
=> Format and such

.github/workflows/ci.yml, .replit, flake.nix, infra/bff/friends/__tests__/llm.test.ts, infra/bff/friends/ci.bff.ts, infra/bff/friends/llm.bff.ts, infra/bff/friends/test.bff.ts, lib/BfIsographFragmentReader.tsx, packages/app/__generated__/__isograph/BfOrganization/IdentityEditor/output_type.ts, packages/app/__generated__/__isograph/BfOrganization/IdentityEditor/param_type.ts, packages/app/__generated__/__isograph/BfOrganization/IdentityEditor/resolver_reader.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeator/entrypoint.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeator/param_type.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeator/resolver_reader.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorVoice/entrypoint.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorVoice/param_type.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorVoice/resolver_reader.ts, packages/app/__generated__/__isograph/iso.ts, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedIn/LoggedInView.tsx, packages/app/components/BfOrganization/IdentityEditor.tsx, packages/app/contexts/RouterContext.tsx, packages/app/contexts/__tests__/RouterContext.test.tsx, packages/app/entrypoints/EntrypointTwitterIdeator.ts, packages/app/entrypoints/EntrypointTwitterIdeatorEvents.ts, packages/app/entrypoints/EntrypointTwitterIdeatorVoice.ts, packages/app/entrypoints/EntrypointTwitterIdeatorWorkshop.ts, packages/app/routes.ts, packages/bfDb/models/BfOrganization.ts, packages/web/tools.tsx, packages/web/web.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/187).
* __->__ #187
* #186
* #185
* #184
* #183
* #182
* #181
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/187)
=> Unblock the bros

.github/workflows/ci.yml, .gitignore, flake.lock, flake.nix, infra/bff/friends/ci.bff.ts, packages/app/contexts/__tests__/RouterContext.test.tsx
=> CI in github!

infra/bff/friends/devTools.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/189)
=> Set username

packages/app/__generated__/__isograph/BfCurrentViewerLoggedIn/EditVoice/param_type.ts, packages/app/__generated__/__isograph/iso.ts, packages/app/components/BfOrganization/SuggestionsPage.tsx, packages/bfDs/const.tsx, static/appStyle.css, static/toolsStyle.css
=> [wip] suggestions style tweaks

packages/web/tools.tsx
=> fix copy github code so it doesn't alert

packages/app/__generated__/__isograph/BfOrganization/SimpleComposer/output_type.ts, packages/app/__generated__/__isograph/BfOrganization/SimpleComposer/param_type.ts, packages/app/__generated__/__isograph/BfOrganization/SimpleComposer/resolver_reader.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorCompose/entrypoint.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorCompose/output_type.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorCompose/param_type.ts, packages/app/__generated__/__isograph/Query/EntrypointTwitterIdeatorCompose/resolver_reader.ts, packages/app/__generated__/__isograph/iso.ts, packages/app/components/BfOrganization/HistorySidebar.tsx, packages/app/components/BfOrganization/Sidebar.tsx, packages/app/components/BfOrganization/SimpleComposer.tsx, packages/app/components/BfOrganization/Workshopping.tsx, packages/app/entrypoints/EntrypointTwitterIdeator.ts, packages/app/entrypoints/EntrypointTwitterIdeatorCompose.ts, packages/app/routes.ts
=> UI refactor for mvp launch

packages/bfDb/classes/BfCurrentViewer.ts, packages/bfDb/classes/BfErrorNode.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/206).
* __->__ #206
* #205
=> Make a new dangerous cv creation

packages/app/components/BfBlog/BlogFrame.tsx, packages/app/components/BfCurrentViewer/Blog.tsx, packages/app/components/BfOrganization/Sidebar.tsx, packages/app/components/BfOrganization/SimpleComposer.tsx, packages/app/components/BfOrganization/Workshopping.tsx, packages/app/components/Header/SubpageHeaderTitle.tsx, packages/bfDs/components/BfDsCopyButton.tsx, packages/graphql/graphqlContext.ts, static/appStyle.css, static/toolsStyle.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/213).
* __->__ #213
* #212
=> blog frame for blog list

infra/bff/friends/devTools.bff.ts, packages/graphql/graphqlContext.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/215).
* __->__ #215
* #214
=> Query for cv's organization

packages/logger.ts, packages/web/tools.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/216)
=> Logspew fixes

deno.jsonc, infra/bff/friends/__tests__/llm.test.ts, infra/bff/friends/llm.bff.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/226).
* #229
* __->__ #226
* #227
=> Update bff llm to work with claude

packages/app/pages/PageUIDemo.tsx, packages/bfDs/components/BfDsButton.tsx, packages/bfDs/const.tsx, packages/bfDs/demo/Buttons.tsx, static/bfDsStyle.css
=> refactor BfDsButton

packages/bfDb/__tests__/bfDb.test.ts, packages/bfDb/bfDb.ts, packages/bfDb/classes/BfNodeBase.ts, packages/bfDb/coreModels/BfNode.ts
=> bfDb add query

packages/bfDb/classes/BfEdgeBase.ts, packages/bfDb/coreModels/BfEdge.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/232).
* #233
* __->__ #232
=> Split BfEdge into a base class

.replit, infra/bff/friends/devTools.bff.ts, packages/app/components/BfCurrentViewer/Home.tsx, packages/app/entrypoints/EntrypointHome.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/239).
* __->__ #239
* #238
=> Set up login differently for github

infra/bff/friends/devTools.bff.ts, infra/bff/friends/llm.bff.ts, packages/app/components/AppSidebar.tsx, packages/app/components/BfCurrentViewer/Home.tsx, packages/featureFlags/featureFlagsList.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/250).
* __->__ #250
* #249
* #248
=> Create git directory

infra/bff/friends/devTools.bff.ts.new, packages/app/__generated__/__isograph/BfOrganization/BlogRevisionsSidebar/output_type.ts, packages/app/__generated__/__isograph/BfOrganization/BlogRevisionsSidebar/param_type.ts, packages/app/__generated__/__isograph/BfOrganization/BlogRevisionsSidebar/resolver_reader.ts, packages/app/__generated__/__isograph/BfOrganization/FormatterEditor/param_type.ts, packages/app/__generated__/__isograph/BfOrganization/FormatterEditor/resolver_reader.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/entrypoint.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/output_type.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/param_type.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/parameters_type.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/resolver_reader.ts, packages/app/__generated__/__isograph/Query/entrypointFormatterEditor/entrypoint.ts, packages/app/__generated__/__isograph/iso.ts, packages/app/ai/reviseBlog.ts, packages/app/components/BfOrganization/BlogRevisionsSidebar.tsx, packages/app/components/BfOrganization/FormatterEditor.tsx, packages/app/components/BfOrganization/FormatterEditorPanel.tsx, packages/app/mutations/ReviseBlog.ts, packages/bfDb/models/BfOrganization.ts, packages/graphql/__generated__/_nexustypes.ts, packages/graphql/__generated__/schema.graphql, packages/graphql/types/graphqlBfOrganization.ts, static/appStyle.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/252).
* __->__ #252
* #251
=> Added styling

AGENT.md, deno.lock, infra/bin/claude, package.json
=> Welcome claude command

AGENT.md, content/documentation/product/roadmap/0.0.0/twitter-voice/components/VoiceDetails.tsx, infra/jupyter/BaseComponent.tsx, packages/app/components/BfBlog/BlogPostList.tsx, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoginAndRegisterForm.tsx, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoginButton.tsx, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/RegisterButton.tsx, packages/app/components/BfOrganization/EditIdentity.tsx, packages/app/components/BfOrganization/HistorySidebar.tsx, packages/app/components/BfOrganization/Topic.tsx, packages/app/components/ContentOS/LeftSideBar.tsx, packages/app/components/ContentOS/VoiceSetupStep2.tsx, packages/app/server/components/ServerRenderedPage.tsx, packages/bfDs/components/BfDsButton.tsx, packages/bfDs/components/BfDsButtonConfirmation.tsx, packages/bfDs/components/BfDsList.tsx, packages/bfDs/components/BfDsPassword.tsx, packages/bfDs/components/BfDsSpinner.tsx, packages/bfDs/components/BfDsTabs.tsx, packages/bfDs/components/BfDsTodos.tsx, packages/bfDs/components/BfDsTooltip.tsx, packages/bfDs/components/demo/KitchenSink.tsx, packages/bfDs/demo/Buttons.tsx, replit.nix
- Improved project documentation with clearer instructions and additional information
- Manually reviewed all content for accuracy
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/270).
* __->__ #270
* #269
=> Update AGENT.md documentation

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoginButton.tsx
Original commit changeset: 04d6c989f9e6
=> Back out "Fix login bug"

packages/app/__generated__/__isograph/BfOrganization/BlogRevisionsSidebar/param_type.ts, packages/app/__generated__/__isograph/BfOrganization/BlogRevisionsSidebar/resolver_reader.ts, packages/app/__generated__/__isograph/Query/entrypointFormatterEditor/entrypoint.ts, packages/app/ai/reviseBlog.ts, packages/app/components/BfOrganization/BlogRevisionsSidebar.tsx, packages/bfDb/models/BfOrganization.ts, packages/graphql/__generated__/_nexustypes.ts, packages/graphql/__generated__/schema.graphql, packages/graphql/types/graphqlBfOrganization.ts, static/appStyle.css
=> improve blog AI and styling

AGENT.md, deno.jsonc, packages/bfDb/backend/DatabaseBackend.ts, packages/bfDb/backend/DatabaseBackendPostgres.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/275).
* __->__ #275
* #274
* #272
=> DB backend

packages/app/components/BfOrganization/BlogRevisionsSidebar.tsx, packages/app/components/BfOrganization/FormatterEditorPanel.tsx, packages/bfDs/components/BfDsCheckbox.tsx, packages/bfDs/components/BfDsForm/BfDsFormCheckbox.tsx, packages/bfDs/components/BfDsTextArea.tsx, packages/bfDs/components/demo/Form.tsx, static/bfDsStyle.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/289).
* __->__ #289
* #288
=> add checkbox to revisions and text area

AGENT.md, __TEMPLATE__.ipynb, packages/bfDb/classes/BfEdgeBase.ts, packages/bfDb/classes/BfEdgeInMemory.ts, packages/bfDb/classes/BfNodeBase.ts, packages/bfDb/classes/__tests__/BfEdgeBaseTest.ts, packages/bfDb/classes/__tests__/BfEdgeInMemory.test.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/292).
* __->__ #292
* #291
* #286
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/292)
=> BfEdgeInMemory

AGENT.md, packages/bfDb/classes/__tests__/BfEdgeBaseTest.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/293)
=> Tell the agent to do tdd

packages/bfDb/classes/BfNodeBase.ts, packages/bfDb/classes/__tests__/BfNodeBaseTest.ts, packages/bfDb/coreModels/BfNode.ts, packages/bfDb/coreModels/__tests__/BfNode.test.ts, packages/bfDb/models/BfBlog.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/294)
=> Align type signatures

AGENT.md, infra/bff/friends/c.bff.ts, infra/bff/friends/t.bff.ts
=> bff c and bff t

AGENT.md, infra/bff/friends/ci.bff.ts, packages/bfDb/classes/BfEdgeBase.ts, packages/bfDb/classes/BfEdgeInMemory.ts, packages/bfDb/classes/BfNodeBase.ts, packages/bfDb/classes/BfNodeInMemory.ts, packages/bfDb/classes/__tests__/BfEdgeBaseTest.ts, packages/bfDb/classes/__tests__/BfNodeBaseTest.ts, packages/bfDb/classes/__tests__/BfNodeInMemory.test.ts, packages/bfDb/coreModels/BfEdge.ts, packages/bfDb/coreModels/BfNode.ts, packages/bfDb/coreModels/__tests__/BfEdge.test.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/300).
* __->__ #300
* #299
* #298
* #297
=> BfEdge tests

AGENT.md
- Added instructions for new developers to set up the Replit Assistant
- Added custom instruction to check AGENT.md for helpful tips
- Ensured the assistant will suggest updating documentation with new discoveries
- Verified formatting with bff f
- Confirmed the instructional content is clear and helpful for new users
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/317)
=> Add Replit Assistant setup to AGENT.md

AGENT.md, README.md, content/documentation/community/backlog/show-hn-draft.md, content/documentation/community/backlog/show-hn-plan.md, content/documentation/community/contributing.md
- Added a new section "Finding Work Items" to AGENT.md listing the canonical locations to find tasks to work on
- Updated the project introduction in README.md to focus on developer experience
- Verified content displays correctly in AGENT.md
- Confirmed formatting is consistent with existing documentation
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/318)
=> Add documentation for finding work items

AGENT.md, packages/bfDb/classes/BfNodeOnDisk.ts
- Added a new "Development Philosophies" section to AGENT.md with detailed information about the "Worse is Better" approach
- Explained the core principles of "Worse is Better": simplicity, correctness, consistency, and completeness
- Described why this philosophy works well and its application in Content Foundry
- Added a subsection explaining how "Worse is Better" pairs naturally with Test-Driven Development
- Verified documentation renders correctly in Markdown
- Ensured proper section organization and formatting
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/320).
* __->__ #320
* #316
* #319
- - -
Perform an AI-assisted review on [<img …
=> Add "Development Philosophies" section to AGENT.md

AGENT.md
- Added "The Cult of Done Manifesto" section with 13 principles and application in Content Foundry development
- Enhanced commit protocol by adding checks for missing diff and CI results files
- Improved error handling in the BFA commit process with clearer instructions
- Verified content is properly formatted and consistent with the existing document
- Confirmed new guidance aligns with project development philosophy
=> Update AGENT.md with Cult of Done Manifesto and commit process improvements

AGENT.md
- Removed the bff ci command from the precommit protocol in AGENT.md
- Updated protocol description to clarify it no longer runs CI process
- Fixed formatting and code block indentation in protocol documentation
- Verified that the updated protocol documentation is clear and consistent
- Tested protocol by running the precommit commands without the CI step
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/334)
=> Update precommit protocol by removing bff ci

infra/bff/friends/build.bff.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/336)
=> ENABLE_DEBUG_LOGGER

packages/bfDs/components/BfDsButton.tsx, packages/bfDs/components/BfDsDropdownSelector.tsx, packages/bfDs/components/BfDsTooltip.tsx, packages/bfDs/components/BfDsTooltipMenu.tsx, packages/bfDs/lib/tooltips.ts
* Refactored tooltip menus out of tooltips
https://github.com/user-attachments/assets/8c57288a-9337-4d1e-8a4b-eaf41ed6d8a4
- Reformatted code with deno fmt
- Fixed code style and indentation in BfDsButton.tsx
- This change only involves code formatting and no functional changes
- Verified that the component continues to render correctly
- No functional changes were made, only formatting adjustments
=> Refactor tooltips

AGENT.md
Tried to rework the agent file with the first version of our upcoming agent card approach.
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/350)
=> Rework agent file

packages/app/__generated__/__isograph/Mutation/CreateVoice/entrypoint.ts, packages/app/__generated__/__isograph/Mutation/CreateVoice/param_type.ts, packages/app/__generated__/__isograph/Mutation/CreateVoice/resolver_reader.ts, packages/app/__generated__/__isograph/Mutation/MakeTweets/entrypoint.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/entrypoint.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/param_type.ts, packages/app/__generated__/__isograph/Mutation/ReviseBlog/resolver_reader.ts, packages/app/components/BfOrganization/IdentityEditor.tsx, packages/app/mutations/CreateVoice.tsx, packages/app/mutations/ReviseBlog.ts, packages/bfDb/classes/BfCurrentViewer.ts, packages/graphql/__generated__/_nexustypes.ts, packages/graphql/__generated__/schema.graphql, packages/graphql/types/graphqlBfOrganization.ts
- Modified packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedIn/LoggedInView.tsx to redirect to `/twitter` instead of previous unspecified path
- This ensures users are redirected to the Twitter interface upon login
- Verified redirection works properly by testing the login flow
- Confirmed that users land on the Twitter interface after authentication
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/355).
* __->__ #355
* #354
* #353
=> Update LoggedInView redirect target path

packages/app/components/AppSidebar.tsx
hid twitter, captions, and UI
Summary:
Test Plan:
=> Hide non-launch stuff in sidebar

infra/bff/friends/build.bff.ts
=> add DATABASE_BACKEND to build so try demo redirects

AGENT.md, infra/bff/friends/build.bff.ts, infra/bff/friends/ci.bff.ts, infra/bff/friends/t.bff.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/364).
* #365
* #363
* __->__ #364
* #362
* #366
=> Simple typechecks

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/LoggedOutView.tsx, packages/app/components/BfCurrentViewer/Home.tsx, packages/app/components/BfOrganization/FormatterSidebar.tsx, packages/app/components/BfOrganization/IdentityEditor.tsx
squashed launch bugs. styling, routing, etc
- Verified styling changes work as expected
=> Update styling in BfDsStyle.css

packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedIn/LoggedInView.tsx
fixed routing issue
Summary:
Test Plan:
=> /login when logged in goes to /formatter

packages/app/__generated__/__isograph/BfCurrentViewer/Home/param_type.ts, packages/app/__generated__/__isograph/BfCurrentViewer/Home/resolver_reader.ts, packages/app/__generated__/__isograph/Query/EntrypointHome/entrypoint.ts, packages/app/components/BfCurrentViewer/BfCurrentViewerLoggedOut/DemoButton.tsx, packages/app/components/BfCurrentViewer/Home.tsx
=> home page loads demo button

packages/app/components/BfCurrentViewer/Home.tsx
=> bug fix for home page button

content/marketing/show-hn.md, packages/app/__generated__/__isograph/BfCurrentViewer/DemoButton/output_type.ts, packages/app/__generated__/__isograph/BfCurrentViewer/DemoButton/param_type.ts, packages/app/__generated__/__isograph/BfCurrentViewer/DemoButton/resolver_reader.ts, packages/app/__generated__/__isograph/BfCurrentViewer/Home/param_type.ts, packages/app/__generated__/__isograph/BfCurrentViewer/Home/resolver_reader.ts, packages/app/__generated__/__isograph/BfCurrentViewerLoggedOut/DemoButton/output_type.ts, packages/app/__generated__/__isograph/BfCurrentViewerLoggedOut/LoggedOutView/param_type.ts, packages/app/__generated__/__isograph/BfCurrentViewerLoggedOut/LoggedOutView/resolver_reader.ts, packages/app/__generated__/__isograph/Query/EntrypointHome/entrypoint.ts, packages/app/__generated__/__isograph/iso.ts, packages/app/components/BfContentItem/ContentItem.tsx, packages/app/components/BfCurrentViewer/DemoButton.tsx, packages/app/components/BfCurrentViewer/Home.tsx, packages/bfDb/utils/pathUtils.ts, packages/graphql/__generated__/_nexustypes.ts, packages/graphql/types/graphqlBfContentCollection.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/387).
* __->__ #387
* #388
* #386
=> start updating homepage

packages/app/components/BfOrganization/FormatterEditorPanel.tsx
=> add demo post

deno.lock, package.json, packages/app/components/BfContentItem/ContentItem.tsx
=> Render markdown on homepage

packages/app/components/BfCurrentViewer/Home.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/391)
=> viewport fixes

static/appStyle.css
=> added some padding to homepage content for mobile

content/biglittletech/2025/03/little-tech-doesn't-mean-small.md
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/396).
* #397
* __->__ #396
=> First blt post

packages/bfDb/models/BfContentCollection.ts, packages/bfDb/models/__tests__/BfContentCollection.test.ts, replit.nix
=> Hide dotfiles in collections

AGENT.md, infra/bff/friends/build.bff.ts, infra/bff/friends/llm.bff.ts, infra/bff/friends/remote.bff.ts, packages/app/components/IsographHeader.tsx, packages/app/constants/deploymentEnvs.ts, packages/bfDb/classes/BfNodeBase.ts, packages/bfDb/classes/__tests__/BfNodeBaseTest.ts, packages/bfDb/utils/contentUtils.ts, packages/web/handlers/domainHandler.ts, packages/web/handlers/mainHandler.ts, packages/web/handlers/requestHandler.ts, packages/web/handlers/routeHandlers.ts, packages/web/handlers/staticHandler.ts, packages/web/routes/appRoutes.ts, packages/web/routes/isographRoutes.ts, packages/web/routes/routeRegistry.ts, packages/web/web.tsx
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/413).
* __->__ #413
* #412
* #411
* #410
* #407
* #406
* #408
* #409
=> Refactor part 3

packages/web/handlers/__tests__/domainHandler.test.ts, packages/web/handlers/domainHandler.ts
=> render domain mdx as html

packages/cfDs/base.css, packages/web/handlers/__tests__/domainHandler.test.ts, packages/web/handlers/domainHandler.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/421).
* __->__ #421
* #420
=> Update domain handler to handle static file serving

flake.lock, flake.nix
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/405)
=> Update flake for local

packages/app/__generated__/__isograph/BfCurrentViewer/Home/param_type.ts, packages/app/__generated__/__isograph/BfCurrentViewer/Home/resolver_reader.ts, packages/app/__generated__/__isograph/Query/EntrypointHome/entrypoint.ts, packages/app/components/BfCurrentViewer/Home.tsx
=> Real home fix

packages/web/handlers/domainHandler.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/content-foundry/content-foundry/436)
=> don't 500 probably

packages/app/components/lexical/LexicalDemo.tsx, packages/app/components/lexical/plugins/ContentFoundry.ts, packages/app/components/lexical/plugins/ContentFoundryPlugin.tsx, packages/app/components/lexical/themes/SampleEditorTheme.ts, packages/bfDs/components/BfDsButton.tsx, static/appStyle.css, static/lexicalStyle.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/content-foundry/content-foundry/pull/442).
* __->__ #442
* #440
* #439
=> Example –> Sample

docs/0.0.0/llm-analytics.md
This commit removes the "Appendix: Technical Definitions" section from the `llm-analytics.md` document. The removal includes all TypeScript interface definitions related to the configuration, analytics options, storage options, client wrappers, routing rules, LLM interaction data, identity cards, and behavior cards. This change aims to streamline the document by eliminating technical details that may not be necessary for the initial implementation plan. The focus is maintained on the core concepts, design, and implementation phases to ensure clarity and accessibility for a broader audience.
1. Confirm the `llm-analytics.md` document is updated and the "Appendix: Technical Definitions" section is completely removed.
2. Review the document to ensure the remaining content is coherent without …
=> Remove Technical Definitions from LLM Analytics Document

AGENT.md, README.md, docs/0.0.0/behavior-cards.md, docs/0.0.0/llm-analytics.md, docs/wut.md
SUMMARY:
This commit introduces a new documentation structure called "Behavior Cards" to the Bolt Foundry project. Behavior Cards are designed to standardize workflows, codify best practices, and guide implementation in the development of LLM systems. The changes include:
1. Updates to `AGENT.md` to describe the new location and format of Behavior Cards.
2. Updates to `README.md` to include Behavior Cards as part of the project's key components.
3. Creation of a new document `behavior-cards.md` that comprehensively describes the purpose, structure, and types of Behavior Cards.
4. Addition of a terminology guide `wut.md` to clarify terminology distinctions such as "samples" vs "examples" and "Identity Card" vs "Behavior Card".
5. Minor correction in `llm-analytics.md` for grammatical …
=> Introduce Behavior Cards for Standardizing LLM Development Protocols

docs/desks-project-plan.md
The recent changes to `desks-project-plan.md` involve the removal of the "User Authentication Test" section from the document's test plan. This decision was likely made to streamline the testing focus and possibly because authentication is handled by existing infrastructure, making it unnecessary to include in the project's specific test plan. The other sections have been renumbered accordingly, ensuring clarity and continuity in the test strategy for the Desks application. These adjustments help maintain a clear and concise testing framework that aligns with the core objectives of the project.
1. Review the updated `desks-project-plan.md` to ensure the removal of the "User Authentication Test" is correctly reflected.
2. Verify that the renumbering of the remaining test plan sections …
=> Remove User Authentication Test from Desks Project Plan

agents/behaviors/technical-implementation-plans.bhc.md, apps/desks/bfdb/README.md, apps/desks/components/README.md, apps/desks/docs/0.0.0/README.md, apps/desks/docs/0.0.0/desks-implementation-plan.md, apps/desks/docs/0.0.0/desks-project-plan.md, apps/desks/docs/0.0.1/desks-phase-2-implementation-plan.md, apps/desks/docs/0.0.2/desks-phase-3-implementation-plan.md, apps/desks/docs/desks-project-plan.md, apps/desks/graphql/README.md
This commit adds four new README files to the Desks project under various directories: `bfdb`, `components`, `docs/0.0.0`, and `graphql`. Each README provides a brief overview of the directory's purpose and contents, aligning with project standards. The `bfdb` directory's README explains it houses database models for the Desks project. The `components` README details the organization of React components, emphasizing the separation between Desks-specific and shared reusable components. The documentation section includes an overview of the project's purpose and available documents, as well as the overall project structure. Lastly, the `graphql` README specifies that GraphQL type definitions should reside in this directory.
These changes aim to improve the project's maintainability by …
=> Add README files for Desks project structure and guidelines

agents/behaviors/coding.bhc.md
This commit updates the `coding.bhc.md` behavior document by adding a section detailing the directory structure that each app should follow. The newly added guidelines specify that each app's structure should be similar to the main boltFoundry app, consisting of directories for `components`, `contexts`, `hooks`, `utils`, `entrypoints`, and `__generated__`. This change aims to promote consistency and improve maintainability across different app components by ensuring a standardized organizational structure.
1. Open the `coding.bhc.md` document.
2. Verify that the new directory structure guidelines are present under the relevant section.
3. Ensure the directory names and descriptions are clear and accurately reflect the intended structure.
- - -
Perform an AI-assisted review on [<img …
=> Add app directory structure guidelines to coding behavior doc

apps/boltFoundry/components/BfCurrentViewer/Home.tsx, static/appStyle.css
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/511)
=> mobile friendly video

agents/behaviors/docs-directory.bhc.md, agents/behaviors/monorepo-structure.bhc.md, agents/behaviors/phased-project-plans.bhc.md, agents/behaviors/technical-implementation-phases.bhc.md
This commit introduces four new behavior cards, each defining standardized protocols for organizing and documenting project phases and monorepos. The added files are:
1. `docs-directory.bhc.md`: Outlines a protocol for structuring documentation directories, using semantic versioning to track implementation phases, ensuring clear document hierarchy, and maintaining continuity across project documents.
2. `monorepo-structure.bhc.md`: Describes the organization of code within a monorepo, detailing the directory structure for applications, packages, and infrastructure. It emphasizes consistent naming conventions, shared tooling, and documentation integration.
3. `phased-project-plans.bhc.md`: Provides guidelines for creating project plans across multiple development phases. It stresses the …
=> Add documentation protocols for project organization and phases

.replit, infra/bff/friends/build.bff.ts, infra/bff/friends/land.bff.ts
This commit introduces several enhancements to the build process and infrastructure files. In `.replit`, the build command is commented out, possibly to streamline the deployment process when using Cloud Run. In `infra/bff/friends/build.bff.ts`, new helper functions are added to monitor system resources such as memory, disk, and CPU usage. These functions are used to log resource usage at various stages of the build process, providing real-time insights into the system's performance. Additionally, continuous logging is implemented during the build to track resource usage over time. In `infra/bff/friends/land.bff.ts`, a new step is added to run CI checks before committing changes. This ensures that potential issues are caught early, enhancing the reliability of the build process.
1. …
=> Add resource monitoring and CI checks to build process

apps/bfDs/components/BfDsForm/__tests__/BfDsForm.test.tsx, apps/bfDs/components/BfDsForm/__tests__/BfDsFormSubmitButton.test.tsx, apps/bfDs/components/BfDsForm/__tests__/BfDsFormTextInput.test.tsx, apps/bfDs/components/BfDsForm/__tests__/BfDsFormToggle.test.tsx, apps/bfDs/components/__tests__/BfDsBreadcrumbs.test.tsx, apps/bfDs/components/__tests__/BfDsButton.test.tsx, apps/bfDs/components/__tests__/BfDsCallout.test.tsx, apps/bfDs/components/__tests__/BfDsCheckbox.test.tsx, apps/bfDs/components/__tests__/BfDsCopyButton.test.tsx, apps/bfDs/components/__tests__/BfDsInput.test.tsx, deno.jsonc, deno.lock, infra/docs/ui-testing/backlog.md, infra/docs/ui-testing/project-plan.md, infra/testing/ui-testing.ts
This commit introduces a new test file `BfDsCopyButton.test.tsx` for the `BfDsCopyButton` component within the `bfDs` application. The tests cover the rendering of the button with default text, custom button text, and a specified button kind. These tests ensure that the component behaves as expected under these various configurations. The file uses Deno's testing framework along with some utility functions from `infra/testing/ui-testing.ts` and assertions from the standard library.
The tests include:
- Verifying that the button renders with the default text "Copy".
- Verifying that the button renders with custom text when provided.
- Checking that the button renders with the specified kind and applies the correct styles.
Note: Testing the actual copy functionality is not included here due …
=> Add unit tests for BfDsCopyButton component

apps/boltFoundry/components/BfCurrentViewer/Home.tsx, apps/boltFoundry/mutations/JoinWaitlist.tsx
This commit refactors the waitlist form handling in the `Home.tsx` component. The primary changes include extracting the waitlist form logic into a separate `WaitlistForm` component. This encapsulation improves code readability and separation of concerns. The state handling for form submission and error management has been enhanced with dedicated `formSubmitting` and `error` states, respectively. Additionally, the error message display logic has been refined to improve user feedback. The mutation logging level in `JoinWaitlist.tsx` has been changed from `info` to `debug` for better log management in production.
1. Navigate to the current viewer home page and trigger the waitlist form.
2. Fill in the form fields and submit to ensure the form submits successfully.
3. Trigger an error …
=> Refactor waitlist form and enhance error handling

apps/bfDs/components/BfDsButton.tsx, apps/bfDs/components/__tests__/BfDsButton.test.tsx
This commit introduces class names to the `BfDsButton` component for better CSS targeting. Specifically, class names `bfds-button-icon`, `bfds-button-text`, and `bfds-button-icon-right` have been added to their respective `div` elements. This change allows for more flexible styling and easier manipulation of button parts.
Additionally, the test suite for `BfDsButton` has been significantly expanded. New tests verify that:
- Buttons render with correct variant styles (`primary`, `secondary`, `accent`, `alert`).
- Buttons render with correct size attributes for both regular and icon buttons.
- Buttons render correctly with icons only, text only, or both.
- HTML attributes such as `aria-label`, `autofocus`, and `name` are correctly passed through to the button element.
These enhancements …
=> Add class names to BfDsButton and enhance test coverage

.github/workflows/publish-dev.yml
This commit enhances the GitHub Actions workflow for the development publish process by integrating the use of Nix shell caching. The changes include:
- Modifying the 'Update version', 'Build package', 'Publish to npm', and 'Publish package to jsr' steps to run within a Nix development environment.
- Utilizing a cached Nix profile to improve the efficiency and consistency of the development shell environment across multiple workflow runs.
- Ensuring that the commands are executed from the root of the GitHub workspace for consistency.
The integration of Nix ensures that the environment in which these steps are executed is more controlled and reproducible, reducing the likelihood of environment-related issues and improving the overall reliability of the continuous integration process.
1. …
=> Integrate Nix shell caching into publish-dev workflow

.github/workflows/publish-dev.yml
This commit modifies the `.github/workflows/publish-dev.yml` workflow file to enhance security and authentication handling. The changes include setting permissions for `id-token` to `write` and `contents` to `read`, which are necessary for secure token management and repository content access within the GitHub Actions environment. Additionally, an environment variable `DENO_AUTH_TOKENS` is set to `true` to facilitate authentication during the Deno package publishing process. These adjustments aim to improve the security posture of the CI/CD pipeline by explicitly defining permissions and ensuring authentication tokens are correctly handled.
1. Trigger the GitHub Actions workflow to ensure it runs without errors.
2. Verify that the Deno package is published successfully, indicating proper …
=> Update GitHub Actions workflow to enhance security and auth

.github/workflows/publish-dev.yml, packages/bolt-foundry/npm/esm/bolt-foundry.d.ts, packages/bolt-foundry/npm/esm/bolt-foundry.js, packages/bolt-foundry/npm/package-lock.json, packages/bolt-foundry/npm/package.json, packages/bolt-foundry/npm/script/bolt-foundry.d.ts, packages/bolt-foundry/npm/script/bolt-foundry.js
This commit comments out the build and publish steps in the `publish-dev.yml` GitHub Actions workflow file. These steps include building the package using `nix` and publishing it to both npm and jsr. The intention behind commenting out these lines is likely to prevent automated builds and publishing during development, which might be unnecessary or could lead to unintentional overwrites. Additionally, the version number in `package-lock.json` and `package.json` has been updated from `0.0.0-dev.0` to `0.0.0`. Minor formatting changes were made in the TypeScript type definitions and JavaScript files within the `bolt-foundry` package to improve readability and maintain consistency.
1. Ensure that the commented-out steps in the GitHub Actions workflow do not execute during development builds. …
=> Comment out dev package build and publish steps in GitHub workflow

packages/bolt-foundry/bin/dnt.ts
This commit refactors the `dnt.ts` script to dynamically resolve paths for the `outDir` and `entryPoints` using `import.meta.resolve`. This change replaces the hardcoded directory paths with resolved paths, ensuring that the script can dynamically determine the correct paths for building the project. This approach not only enhances the flexibility and portability of the script but also reduces the risk of path-related errors, especially in diverse environments or when the project structure changes.
1. Run the `dnt.ts` script to verify that the project builds successfully without errors.
2. Check that the output is correctly placed in the `npm` directory.
3. Ensure that the resolved entry points are correctly used in the build process.
4. Verify that the build process functions as expected …
=> Refactor dnt.ts to use dynamic path resolution for entryPoints

apps/contacts/client/src/components/ContactTable.tsx, apps/contacts/client/src/components/EmailActivity.tsx, apps/contacts/client/src/components/ui/toast.tsx, apps/contacts/client/src/hooks/use-toast.ts, apps/contacts/server/routes.ts, apps/contacts/server/services/email.ts, apps/contacts/shared/schema.ts
This commit introduces several enhancements and updates across the contacts application:
1. **ContactTable Component**:
- Replaced button actions for managing contact status with a `DropdownMenu` for better user experience.
- Added new options to send welcome emails and mark contacts as contacted.
- Improved accessibility by adding screen reader texts.
2. **EmailActivity Component**:
- Updated to filter contacts with a specific `emailSentAt` timestamp for recent email activity.
3. **Toast Component & Hook**:
- Adjusted the delay for toast removal from 1,000,000ms to 2,000ms for better usability.
- Moved `toastTimeouts` and `addToRemoveQueue` functions for improved code structure.
4. **Database Migration**:
- Added initial migration script to set up `contacts`, `email_settings`, and …
=> Improve Contact Management and Implement Database Schema

agents/behaviors/tdd.bhc.md
This commit introduces a comprehensive Test-Driven Development (TDD) protocol to the Bolt Foundry project. The guidelines emphasize using Deno's native testing capabilities to maintain high code quality and prevent regressions. The document outlines the purpose of TDD, testing approaches with Deno's standard tools, test organization, the Red-Green-Refactor workflow, various test types (unit, integration, E2E), best practices, and provides example test cases. The protocol aims to ensure consistent, high-quality testing across the codebase by promoting design through testing, documentation of expected behavior, and supporting confident refactoring.
1. Ensure all new test files are placed in `__tests__` directories adjacent to the code.
2. Verify that test files use the `.test.ts` suffix and …
=> Add TDD protocol guidelines for Bolt Foundry project

apps/collector/docs/backlog.md
This commit introduces a new `backlog.md` document within the `apps/collector/docs` directory. The document outlines potential features, enhancements, and improvements for the Collector application, focusing on a notable feature: the Reverse PostHog Proxy. This feature, although not immediately prioritized, is intended to provide flexibility by allowing clients to use PostHog's native SDKs directly. The document specifies the priority, complexity, and dependencies of the proposed feature, along with its justification and acceptance criteria. The intention is to guide future development once the core Collector implementation is solidified.
1. Verify that the new `backlog.md` file is present in the `apps/collector/docs` directory.
2. Open the file to ensure it contains detailed information …
=> Add backlog document for future Collector features

.replit, apps/contacts/server/routes.ts, apps/internalbf/internalbf.ts
This commit introduces a new health check endpoint at `/api/health` in the contacts service. The endpoint is not protected and responds with a JSON object indicating the health status of the application. This is useful for monitoring and ensuring that the service is running correctly.
1. Start the server and ensure it runs without errors.
2. Make a GET request to `/api/health` and verify that the response is a JSON object with a key of `status` and a value of `healthy`.
3. Confirm that other API endpoints continue to function as expected.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/605).
* __->__ #605
* #604
- - -
Perform an AI-assisted review on [<img …
=> Add health check endpoint to contacts service

apps/internalbf/internalbf.ts
The `handleRequest` function in `internalbf.ts` was modified to be asynchronous. This change improves the efficiency of the code by using `await` to handle the `fetch` call for checking the status of the Contacts CMS API. The previous implementation used a `.then()` chain which is replaced by `await` to keep the code cleaner and more readable. Additionally, a `<meta charset="utf-8">` tag was added to the HTML template to ensure proper character encoding for the HTML response.
1. Run the application and make a request to the endpoint that utilizes the `handleRequest` function.
2. Verify that the log correctly reflects the API request method and URL.
3. Check that the Contacts CMS API status is correctly reported as "online" if the fetch is successful, and "offline" otherwise.
4. Inspect …
=> Make handleRequest async and improve Contacts API health check

.replit, apps/collector/collector.ts
This commit introduces a new `collector` service designed to handle data collection tasks. The changes include:
- A new script `collector.ts` in the `apps/collector` directory, which sets up a basic HTTP server using Deno. It defines routes for data collection, including a main route for receiving JSON or text data.
- The script is executable and includes logic for logging received data and handling errors.
- Updates to the `.replit` configuration file to include a new workflow for running the collector service and a new port allocation for this service.
- An environment variable `APPS_COLLECTOR_PORT` is defined for setting the port on which the collector service runs, defaulting to 8001.
These changes are aimed at creating a dedicated service for data collection to improve modularity and …
=> Add Collector Service for Data Collection and Handling

apps/collector/__tests__/collector.test.ts
This commit introduces integration tests for the collector service to validate its ability to process various types of requests and return appropriate responses. The tests cover handling of JSON data, text data, invalid requests, and requests to non-existent routes. These tests ensure that the collector service behaves as expected under different scenarios, returning the correct status codes and responses.
1. Added a test for JSON data collection, verifying a 200 status code and a successful response.
2. Added a test for text data collection, verifying a 200 status code and a successful response.
3. Added a test for handling invalid requests, verifying a 400 status code and an error response.
4. Added a test for non-existent routes, verifying a 404 status code.
Run the tests using the …
=> Add integration tests for collector service request handling

apps/collector/__tests__/llm-event-tracker.test.ts, apps/collector/collector.ts, apps/collector/llm-event-tracker.ts, deno.jsonc, packages/bolt-foundry/bolt-foundry.ts
This commit introduces PostHog integration for enhanced telemetry tracking in the collector application. Key changes include:
- Added PostHog client initialization in `collector.ts` for event capturing when the API key is available.
- Introduced `getCurrentViewerApiKey()` to obtain the API key from environment variables.
- Modified `trackLlmEvent` function in `llm-event-tracker.ts` to use a structured `TelemetryData` object, replacing individual request and response parameters.
- Improved error handling and logging for LLM requests to ensure accurate telemetry data collection.
- Updated `deno.jsonc` to reorganize import paths and added new type definitions in `bolt-foundry.ts` for OpenAI request and response bodies.
These changes aim to streamline tracking logic and improve observability …
=> Integrate PostHog tracking and refactor LLM event telemetry

infra/gcp/docs/project-plan.md
This commit introduces a new project plan document for setting up Google Cloud Secrets Manager using Terraform, located at `infra/gcp/docs/project-plan.md`. The document outlines the purpose of the project, which is to securely store and manage sensitive configuration data, such as API keys and passwords, within Google Cloud Platform (GCP). This approach leverages Terraform for an automated, version-controlled secrets management system, applicable across all environments.
The document details the project versions, starting with Version 0.1, which focuses on setting up the foundational infrastructure, creating a working Terraform configuration, and implementing initial Secrets Manager deployment. It also includes a testing strategy covering infrastructure, integration, security, and …
=> Add initial project plan for GCP Secrets Manager setup

infra/gcp/docs/0.1/implementation-plan.md
This commit introduces a detailed implementation plan for managing secrets and configuration variables in Google Cloud Platform (GCP) using Terraform. The plan outlines the goals for version 0.1, including securely managing sensitive and non-sensitive data with minimal developer tooling. Key components include setting up the GCP project, configuring the Secrets Manager, integrating with the BFF CLI for operational commands, and establishing CI/CD pipeline integration for Terraform validation. The commit also provides a directory structure for organizing the Terraform configurations and a testing strategy to ensure successful deployment and access controls.
- Run `terraform validate` to ensure the configurations are correct.
- Use BFF CLI commands to verify secret creation, retrieval, and …
=> Add initial GCP secrets and config implementation plan

infra/bff/friends/ai.bff.ts, infra/bff/friends/land.bff.ts
This commit improves the handling of AI-generated responses and the process for editing and committing messages. Key changes include:
1. Enhanced null-safe access to the AI response by using optional chaining and providing a default empty string if the response is unavailable. This prevents potential runtime errors when accessing properties of undefined objects.
2. Modified the workflow to write the AI-generated commit message to a temporary file and open it in the user's preferred editor for further editing. This allows users to adjust the commit message before deciding to proceed with the commit.
3. Adjusted the commit process to use the user-edited message. After editing, the temporary file is read, and its content is split into a title and body for the commit. The temporary file is …
=> Enhance AI response handling and commit message editing

apps/bfDb/classes/BfErrorNode.ts, apps/bfDb/graphql/builder/builder.ts, apps/bfDb/graphql/builder/compiler.ts, apps/bfDb/models/BfOrganization.ts, apps/bfDb/models/BfPerson.ts, apps/bfDb/models/__tests__/BfPerson.test.ts, apps/bfDb/testUtils/testViewers.ts, apps/boltFoundry/docs/0.1/project-plan.md, apps/boltFoundry/docs/backlog.md, infra/bff/friends/ai.bff.ts
This commit introduces a new static method `verifyLogin` in the `BfPerson` class to handle Google OAuth login attempts. The method performs the following steps:
1. Validates that the email parameter matches the Google payload and that the email is verified by Google.
2. Checks if the email's domain is blocked (currently, `gmail.com` is disallowed).
3. Searches for an existing `BfPerson` with the given email. If found, it returns the existing user.
4. If no existing user is found, it creates a new `BfPerson` and a new `BfOrganization`, connecting them with an OWNER edge.
Additionally, the commit updates the GraphQL specs for `BfOrganization` and `BfPerson` to include new fields and relations. The `AnyBfNodeCtor` type was refactored to be more generic, promoting code reusability and type …
=> Add Google OAuth login verification to BfPerson model

apps/bfDb/classes/BfNodeBase.ts, apps/bfDb/coreModels/BfNode.ts, apps/bfDb/graphql/builder/__tests__/builder.test.ts, apps/bfDb/graphql/builder/builder.ts, apps/bfDb/models/__tests__/BfPerson.test.ts
This commit introduces several enhancements to the GraphQL node handling in the BfNodeBase and related classes. The main changes include:
1. **UUID Generation**: A private `_id` field with a getter method is added to generate a unique identifier using the `generateUUID` function when accessed.
2. **GraphQL Specification Updates**: The `defineGqlNode` method in the `BfNodeBase` class is refactored to allow a class to inherit GraphQL specifications (`gqlSpec`) from its parent class if not explicitly defined. This change ensures that the `implements` array in a node's GraphQL specification includes its parent's specification, facilitating better GraphQL schema extension and inheritance.
3. **Removal of Redundant Comments and Code**: Unnecessary comments and outdated code segments have been …
=> Enhance GQL Node Handling with UUIDs and Parent Spec Inheritance

docs/product-plan.md
This commit updates the `product-plan.md` document to revise the milestones and success metrics for the project. Key changes include:
- Introduction of version 0.1 milestone, focusing on enabling user login with Google, with a metric of unique users.
- Reordering and updating milestones from 0.2 to 0.8, each associated with specific metrics such as samples ingested, structured calls made, cards generated, samples reconciled, and DAP (Digital Adoption Platform).
- The core success metric has been clarified to focus on the number of reconciled samples, with additional version-specific metrics introduced to track progress.
- Added explanations and placeholders for future features like heatmap and backtesting with their corresponding metrics.
These changes aim to provide a clearer roadmap for …
=> yUpdate milestones and success metrics in product plan

apps/boltFoundry/docs/login/project-plan.md
This commit updates the project plan for the login integration by transitioning from Phase 0, which focused on a proof of concept with email login, to Phase 1, which will implement Google OAuth. The changes include amending the document to reflect completed tasks under Phase 0 and outlining new tasks required for Phase 1, such as creating a Google OAuth client, implementing a Google Sign-In button, and setting up backend endpoints for authentication. The document also updates the milestones, tasks, and areas of focus to align with the new phase objectives.
👀
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/707).
* #708
* __->__ #707
=> Update project plan for Google OAuth integration phase

.github/workflows/ci.yml
=> ci caching

packages/bolt-foundry/README.md, packages/bolt-foundry/docs/0.1/implementation-plan.md, packages/bolt-foundry/docs/0.2/implementation-plan.md, packages/bolt-foundry/docs/project-plan.md
- update README with `connectBoltFoundry` examples
- use `connectBoltFoundry` in implementation docs
- `bff f` *(fails: command not found)*
- `bff ci` *(fails: command not found)*
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/779)
=> Update docs for connectBoltFoundry

.github/workflows/ci.yml
=> Add debugging to ci for caching

deno.lock, package.json
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/793)
=> update claude code version

infra/bff/__tests__/githubLogger.test.ts, infra/bff/friends/githubAnnotations.ts, infra/bff/githubLogger.ts
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/794).
* #795
* __->__ #794
=> fix a thing

CLAUDE.md, infra/bff/friends/amend.bff.ts
=> Amend shouldn't require a message

.github/workflows/flakehub-publish-rolling.yml
=> Flakehub publish

.github/workflows/flakehub-publish-rolling.yml
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/824)
=> flakehub cache

.flakeignore
- ignore static assets, build and tmp folders
- exclude other large files like `deno.zip` and caches
- `bff f` *(failed: Could not resolve "posthog-node")*
- `bff ci` *(failed: Could not resolve "posthog-node")*
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/835)
=> Add flakeignore to shrink archive size

.flakeignore, .gitignore
=> flakey flakes

apps/bfDb/docs/0.3/implementation-plan.md, apps/bfDb/docs/status.md
Refactor the GraphQL builder roadmap to focus on enhanced barrel files in v0.3.
Changes:
- Updated status.md to mark v0.2 as completed
- Moved previous v0.3 tasks to v0.4 in status.md
- Created new v0.3 plan focused on barrel file system improvements
- Added detailed implementation plan for barrel file enhancements
Test plan:
1. Verify implementation plan follows versioned documentation structure
2. Confirm status.md correctly reflects the updated roadmap
3. Check that technical design details in v0.3 plan align with existing barrel system
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/842)
=> Create GraphQL Builder v0.3 implementation plan

flake.nix
=> Flakehub two

.claude/settings.json, .gitignore, deno.lock, package.json
=> Another update

apps/boltFoundry/components/Formatter.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/876)
=> show og prompt

cards/coding.card.md, cards/implementation-planning.card.md, docs/STATUS.md, docs/product-plan.md, infra/bff/friends/commit.bff.ts, infra/bff/friends/e2e.bff.ts, packages/bolt-foundry/deno.json, packages/get-configuration-var/package.json, packages/logger/package.json
- Update bolt-foundry package from 0.0.21 to 0.1.0
- Update get-configuration-var package from 0.0.1 to 0.1.0
- Update logger package from 0.0.1 to 0.1.0
- Update STATUS.md to reflect v0.1.0 documentation focus
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/914).
* __->__ #914
* #913
* #912
* #911
* #907
=> Update packages to v0.1.0 for documentation milestone

cards/brand-voice.card.md, cards/discover-before-developing.card.md, deno.lock, package.json
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/924).
* __->__ #924
* #923
* #922
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/924)
=> discover before developing

.replit, deno.jsonc, examples/nextjs-sample/README.md, examples/nextjs-sample/pages/api/chat.ts, examples/nextjs-sample/pages/api/regular-chat.ts, examples/nextjs-sample/pages/bolt-foundry-example.tsx, examples/nextjs-sample/pages/chat.tsx, examples/nextjs-sample/pages/index.tsx, examples/nextjs-sample/styles/Chat.module.css, examples/nextjs-sample/tsconfig.json, examples/tsconfig.base.json, examples/tsconfig.nextjs.base.json, flake.nix
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/928).
* __->__ #928
* #927
* #926
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/928)
=> Fix Next.js Link warnings and improve Bolt Foundry example

apps/boltFoundry/components/Home.tsx
=> fix blog button

apps/boltFoundry/components/Docs.tsx, apps/boltFoundry/components/DocsSidebar.tsx, static/bfDsStyle.css, static/landingStyle.css
=> Add real docs

apps/bfDb/graphql/roots/Waitlist.ts, apps/boltFoundry/__generated__/__isograph/Mutation/JoinWaitlist/entrypoint.ts, apps/boltFoundry/__generated__/__isograph/Mutation/JoinWaitlist/output_type.ts, apps/boltFoundry/__generated__/__isograph/Mutation/JoinWaitlist/param_type.ts, apps/boltFoundry/__generated__/__isograph/Mutation/JoinWaitlist/parameters_type.ts, apps/boltFoundry/__generated__/__isograph/Mutation/JoinWaitlist/resolver_reader.ts, apps/boltFoundry/__generated__/__isograph/iso.ts, apps/boltFoundry/__generated__/builtRoutes.ts, apps/boltFoundry/components/Home.tsx, apps/boltFoundry/mutations/JoinWaitlist.tsx, apps/web/routes/routeRegistry.ts, static/landingStyle.css
=> Replace substack form with old waitlist

apps/boltFoundry/components/Docs.tsx, apps/boltFoundry/components/Home.tsx
If you go to /docs, the links would be relative and open /team so now it will go to /docs/team
Summary:
Test Plan:
=> make links absolute

apps/boltFoundry/components/Home.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1015)
=> change code to copy to bf-eval

apps/boltFoundry/components/Docs.tsx
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1017)
=> fix absolute links with extension

apps/boltFoundry/components/DeckVisualization.tsx, apps/boltFoundry/pages/Decks.tsx, apps/boltFoundry/routes.ts, static/appStyle.css, static/landingStyle.css
=> Deck visualization

apps/boltFoundry/components/DeckVisualization.tsx, apps/boltFoundry/lib/deckTypes.ts, apps/boltFoundry/pages/Decks.tsx, apps/boltFoundry/routes.ts, static/landingStyle.css
Summary:
Test Plan:
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1038).
* __->__ #1038
* #1037
=> [deck visualizer] nested corners

customers/munchinsights.com/memos/line-item-extractor-implementation-plan.md
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1049)
=> Implementation plan for spacial extractor

apps/boltFoundry/components/Blog.tsx, apps/boltFoundry/components/BlogList.tsx, apps/boltFoundry/components/BlogPostView.tsx, apps/boltFoundry/components/Docs.tsx, apps/boltFoundry/components/Home.tsx, apps/boltFoundry/components/Nav.tsx, static/landingStyle.css
=> blog paper style, dry nav bar

decks/example-tone-grader.deck.md, decks/example-tone-grader.deck.toml, decks/grader-base.deck.md, decks/grader-base.deck.toml, decks/graders/sports-news-grader.deck.md, decks/graders/sports-news-grader.deck.toml, memos/plans/2025-06-markdown-decks-implementation.md
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1072).
* __->__ #1072
* #1070
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1072)
=> graders for markdown

docs/blog/2025-06-inconsistent-outputs-to-perfect-reliability.md, static/landingStyle.css
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1087)
=> fix block quotes and html characters

apps/aibff/__tests__/backward-compatibility.test.ts, apps/aibff/__tests__/commands/eval.test.ts, apps/aibff/__tests__/commands/index.test.ts, apps/aibff/__tests__/commands/types.test.ts, apps/aibff/__tests__/main.test.ts, apps/aibff/bin/build.ts, apps/aibff/commands/eval.ts, apps/aibff/commands/index.ts, apps/aibff/commands/types.ts, apps/aibff/main.ts, apps/aibff/memos/plans/2025-06-cli-consolidation-plan.md
Document approach for consolidating bff, bff-eval, and aibff into single standardized CLI tool with proper Unix conventions and namespace separation
Changes:
- Create implementation plan following the standard template
- Define goals for unified CLI with standardized argument parsing
- Outline spike/prototype approach in aibff before package extraction
- Include roadmap for phased migration of existing tools
- Focus on discovering patterns through implementation
Test plan:
- Review plan against implementation-planning.card.md template
- Verify all sections are complete and actionable
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1095).
* __->__ #1095
* #1094 …
=> Add CLI consolidation implementation plan

deno.lock, package-lock.json, package.json
=> Upgrade claude code

infra/testing/e2e/setup.ts
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1316)
=> headless mode improvements

deno.jsonc, deno.lock
=> Update claude code

apps/boltfoundry-com/memos/plans/markdown-deck-sample-collection.md
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1473)
=> sample collection

AGENTS.md, apps/boltFoundry/memos/plans/phase-3-ui-implementation.md, deno.lock, docs/blog/2025-06-5-things-about-llms.md, docs/guides/telemetry-api.md, infra/bff/friends/ci-status.bff.ts, infra/bff/friends/fork.bff.ts, memos/guides/billing-implementation-guide.md, memos/plans/monorepo-consolidation-strategy.md, packages/bolt-foundry/README.md
- Add monorepo consolidation strategy to reduce from 11 to 6 apps
- Add billing implementation guide with  minimum spend model
- Add comprehensive telemetry API documentation
- Update bolt-foundry SDK documentation for current capabilities
- Update AGENTS.md with current monorepo structure
- Update phase-3 UI implementation status to completed
- Fix repository name references from content-foundry to bolt-foundry
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1499).
* #1500
* __->__ #1499
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" …
=> docs: add strategic planning and API documentation

.github/workflows/deploy-boltfoundry-com.yml, infra/terraform/hetzner/config/otel_collector.yml, infra/terraform/hetzner/deploy.yml.tpl, memos/plans/2025-07-22-hyperdx-opentelemetry-integration.md
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/bolt-foundry/bolt-foundry/pull/1568).
* __->__ #1568
* #1567
=> Add OpenTelemetry Collector integration with HyperDX

apps/boltfoundry-com/__tests__/e2e/css-loading.test.e2e.ts, apps/boltfoundry-com/__tests__/e2e/ssr.test.e2e.ts, apps/boltfoundry-com/__tests__/e2e/ui-route.test.e2e.ts, apps/boltfoundry-com/components/Home.tsx, apps/boltfoundry-com/components/Nav.tsx, apps/boltfoundry-com/components/WaitlistSection.tsx, static/landingStyle.css
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1590)
=> social icons in header, background, fix e2e tests

apps/bfDs/components/BfDsCheckbox.tsx, apps/bfDs/components/BfDsInput.tsx, apps/bfDs/components/BfDsRadio.tsx, apps/bfDs/components/BfDsRange.tsx, apps/bfDs/components/BfDsSelect.tsx, apps/bfDs/components/BfDsTextArea.tsx, apps/bfDs/components/BfDsToggle.tsx, apps/bfDs/components/__examples__/BfDsCheckbox.example.tsx, apps/bfDs/components/__examples__/BfDsInput.example.tsx, apps/bfDs/components/__examples__/BfDsRadio.example.tsx, apps/bfDs/components/__examples__/BfDsRange.example.tsx, apps/bfDs/components/__examples__/BfDsSelect.example.tsx, apps/bfDs/components/__examples__/BfDsTextArea.example.tsx, apps/bfDs/components/__examples__/BfDsToggle.example.tsx
=> add 'defaultValue/Checked` to form components

static/landingStyle.css
Summary:
Test Plan:
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1592)
=> use hetzner object storage for bg image

.dockerignore, flake.nix
=> create docker ignore

.replit
=> fix bad commit

apps/boltfoundry-com/README.md
Minor update to trigger deployment and test CI/CD pipeline.
- - -
Perform an AI-assisted review on [<img src="https://codepeer.com/logo/CodePeerButton.svg" height="32" align="absmiddle" alt="CodePeer.com"/>](https://codepeer.com/app/prs/github/bolt-foundry/bolt-foundry/1671)
=> docs: Add description to boltfoundry-com README

apps/bfDs/demo/Demo.tsx, apps/boltfoundry-com/components/UIDemo.tsx, apps/boltfoundry-com/contexts/RouterContext.tsx, apps/boltfoundry-com/routes.ts
=> add routing for Demo, fix router wildcards
